SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[NumberToString] (@value int, @size INT) 
RETURNS VARCHAR(20) 
AS 
BEGIN 
	DECLARE @TMP VARCHAR (128); 
	SET @TMP = CAST(@value AS VARCHAR(20)); 
	IF @TMP IS NULL 
		SET @TMP=0; 
	
	WHILE LEN(@TMP)< @SIZE 
		SET @TMP = '0'+@TMP; 
	RETURN @TMP; 
END

GO
