SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[EFORECAST_TIME_VW] as
	SELECT DISTINCT MONTHYEAR =  LEFT(YEAR_QUARTER, 4) + LEFT(convert(varchar, FIRST_DAY, 101), 2), 
	       YEAR = LEFT(YEAR_QUARTER, 4)
	  FROM EFORECAST_TIME (NOLOCK) 
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_TIME_VW] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_TIME_VW] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_TIME_VW] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_TIME_VW] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_TIME_VW] TO [public]
GO
