SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CVO_REGISTER_VW]
AS
SELECT 
	TRXDATE 
	,SUM(CNTINV) AS CNTINV
	,SUM(CNTCRD) AS CNTCRD
	,SUM(NETLIST) AS NETLIST
	,SUM(NETSALES) AS NETSALES
	,SUM(CRDAMT) AS CRDAMT
	,SUM(NETDISC) AS NETDISC
	,SUM(NETTAX) AS NETTAX
	,SUM(NETFREIGHT) AS NETFREIGHT
	,SUM(CRDTAX) AS CRDTAX
	,SUM(CRDFREIGHT) AS CRDFREIGHT
	,X_TRXDATE

FROM CVO_REGISTER_TMP
GROUP BY TRXDATE, X_TRXDATE


GO
GRANT SELECT ON  [dbo].[CVO_REGISTER_VW] TO [public]
GO
GRANT INSERT ON  [dbo].[CVO_REGISTER_VW] TO [public]
GO
GRANT DELETE ON  [dbo].[CVO_REGISTER_VW] TO [public]
GO
GRANT UPDATE ON  [dbo].[CVO_REGISTER_VW] TO [public]
GO
