SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[appoCreate_Vouchers_sp]
AS
DECLARE @result int

	SELECT @result = 0

	INSERT apinpchg
	(
		trx_ctrl_num,
		trx_type,
		doc_ctrl_num,
		apply_to_num,
		user_trx_type_code,
		batch_code,
		po_ctrl_num,
		vend_order_num,
		ticket_num,
		date_applied,
		date_aging,
		date_due,
		date_doc,
		date_entered,
		date_received,
		date_required,
		date_recurring,
		date_discount,
		posting_code,
		vendor_code,
		pay_to_code,
		branch_code,
		class_code,
		approval_code,
		comment_code,
		fob_code,
		terms_code,
		tax_code,
		recurring_code,
		location_code,
		payment_code,
		times_accrued,
		accrual_flag,
		drop_ship_flag,
		posted_flag,
		hold_flag,
		add_cost_flag,
		approval_flag,
		recurring_flag,
		one_time_vend_flag,
		one_check_flag,
		amt_gross,
		amt_discount,
		amt_tax,
		amt_freight,
		amt_misc,
		amt_net,
		amt_paid,
		amt_due,
		amt_restock,
		amt_tax_included,
		frt_calc_tax,
		doc_desc,
		hold_desc,
		user_id,
		next_serial_id,
		pay_to_addr1,
		pay_to_addr2,
		pay_to_addr3,
		pay_to_addr4,
		pay_to_addr5,
		pay_to_addr6,
		attention_name,
		attention_phone,
		intercompany_flag,
		company_code,
		cms_flag,
		process_group_num,
		nat_cur_code,
		rate_type_home,
		rate_type_oper,
		rate_home,
		rate_oper,
		net_original_amt,
		org_id,
		tax_freight_no_recoverable				
	)
	SELECT
		h.trx_ctrl_num,
		h.trx_type,
		h.doc_ctrl_num,
		h.apply_to_num,
		h.user_trx_type_code,
		h.batch_code,
		h.po_ctrl_num,
		h.vend_order_num,
		h.ticket_num,
		h.date_applied,
		h.date_aging,
		h.date_due,
		h.date_doc,
		h.date_entered,
		h.date_received,
		h.date_required,
		h.date_recurring,
		h.date_discount,
		h.posting_code,
		h.vendor_code,
		h.pay_to_code,
		h.branch_code,
		h.class_code,
		h.approval_code,
		h.comment_code,
		h.fob_code,
		h.terms_code,
		h.tax_code,
		h.recurring_code,
		h.location_code,
		h.payment_code,
		h.times_accrued,
		h.accrual_flag,
		h.drop_ship_flag,
		h.posted_flag,
		h.hold_flag,
		h.add_cost_flag,
		h.approval_flag,
		h.recurring_flag,
		h.one_time_vend_flag,
		h.one_check_flag,
		round(h.amt_gross, isnull(g.curr_precision,1.0)),
		round(h.amt_discount, isnull(g.curr_precision,1.0)),
		round(h.amt_tax, isnull(g.curr_precision,1.0)),
		round(h.amt_freight, isnull(g.curr_precision,1.0)),
		round(h.amt_misc, isnull(g.curr_precision,1.0)),
		round(h.amt_net, isnull(g.curr_precision,1.0)),
		round(h.amt_paid, isnull(g.curr_precision,1.0)),
		round(h.amt_due, isnull(g.curr_precision,1.0)),
		round(h.amt_restock, isnull(g.curr_precision,1.0)),
		round(h.amt_tax_included, isnull(g.curr_precision,1.0)),
		h.frt_calc_tax,
		h.doc_desc,
		h.hold_desc,
		h.user_id,
		h.next_serial_id,
		h.pay_to_addr1,
		h.pay_to_addr2,
		h.pay_to_addr3,
		h.pay_to_addr4,
		h.pay_to_addr5,
		h.pay_to_addr6,
		h.attention_name,
		h.attention_phone,
		h.intercompany_flag,
		h.company_code,
		h.cms_flag,
		h.process_group_num,
		h.nat_cur_code,
		h.rate_type_home,
		h.rate_type_oper,
		h.rate_home,
		h.rate_oper,
		round(h.amt_net, isnull(g.curr_precision,1.0)),
		h.org_id,
		round(h.tax_freight_no_recoverable, isnull(g.curr_precision,1.0))				
	FROM #apinpchg h LEFT OUTER JOIN glcurr_vw g (nolock) ON (h.nat_cur_code = g.currency_code)

	IF @@error != 0  
	BEGIN 
		RETURN 100
	END 
	
	INSERT apinpcdt
	(
		trx_ctrl_num,
		trx_type,
		sequence_id,
		location_code,
		item_code,
		bulk_flag,
		qty_ordered,
		qty_received,
		qty_returned,
		qty_prev_returned,
		approval_code,
		tax_code,
		return_code,
		code_1099,
		po_ctrl_num,
		unit_code,
		unit_price,
		amt_discount,
		amt_freight,
		amt_tax,
		amt_misc,
		amt_extended,
		calc_tax,
		date_entered,
		gl_exp_acct,
		new_gl_exp_acct,
		rma_num,
		line_desc,
		serial_id,
		company_id,
		iv_post_flag,
		po_orig_flag,
		rec_company_code,
		new_rec_company_code,
		reference_code,
		new_reference_code,
		org_id,
		amt_nonrecoverable_tax,					
		amt_tax_det						
	)
	SELECT 	d.trx_ctrl_num,
		d.trx_type,
		d.sequence_id,
		d.location_code,
		d.item_code,
		d.bulk_flag,
		d.qty_ordered,
		d.qty_received,
		d.qty_returned,
		d.qty_prev_returned,
		d.approval_code,
		d.tax_code,
		d.return_code,
		d.code_1099,
		d.po_ctrl_num,
		d.unit_code,
		d.unit_price,
		round(d.amt_discount, isnull(g.curr_precision,1.0)),
		round(d.amt_freight, isnull(g.curr_precision,1.0)),
		round(d.amt_tax, isnull(g.curr_precision,1.0)),
		round(d.amt_misc, isnull(g.curr_precision,1.0)),
		round(d.amt_extended, isnull(g.curr_precision,1.0)), 
		round(d.calc_tax, isnull(g.curr_precision,1.0)),
		d.date_entered,
		d.gl_exp_acct,
		d.new_gl_exp_acct,
		d.rma_num,
		d.line_desc,
		d.serial_id,
		d.company_id,
		d.iv_post_flag,
		d.po_orig_flag,
		d.rec_company_code,
		d.new_rec_company_code,
		d.reference_code,
		d.new_reference_code,
		d.org_id,
		round(d.amt_nonrecoverable_tax, isnull(g.curr_precision,1.0)),					
		round(d.amt_tax_det, isnull(g.curr_precision,1.0))						
	FROM #apinpcdt d
		INNER JOIN #apinpchg h ON (h.trx_ctrl_num = d.trx_ctrl_num AND h.trx_type = d.trx_type)
		LEFT OUTER JOIN glcurr_vw g (nolock) ON (h.nat_cur_code = g.currency_code)


	IF @@error != 0  
	BEGIN 
		RETURN 100
	END 

RETURN @result
GO
GRANT EXECUTE ON  [dbo].[appoCreate_Vouchers_sp] TO [public]
GO
