SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[cvo_scm_pb_get_dw_orders_newlist]	@order_no int, 
													@order_ext int, 
													@custkey varchar(10) 
AS
BEGIN

	SELECT	ord_list.order_no,   
		    ord_list.order_ext,   
			ord_list.line_no,   
			ord_list.location,   
			ord_list.part_no,   
			ord_list.description,   
			ord_list.time_entered,   
			ord_list.ordered,   
			ord_list.shipped,   
			ord_list.price,   
			ord_list.price_type,   
			ord_list.note,   
			ord_list.status,   
			ord_list.cost,   
			ord_list.who_entered,   
			ord_list.sales_comm,   
			ord_list.temp_price,   
			ord_list.temp_type,   
			ord_list.cr_ordered,   
			ord_list.cr_shipped,   
			ord_list.discount,   
			ord_list.uom,   
			ord_list.conv_factor,   
			ord_list.void,   
			ord_list.void_who,   
			ord_list.void_date,   
			ord_list.std_cost,   
			ord_list.cubic_feet,   
			ord_list.printed,   
			ord_list.lb_tracking,   
			ord_list.labor,   
			ord_list.direct_dolrs,   
			ord_list.ovhd_dolrs,   
			ord_list.util_dolrs,   
			ord_list.taxable,   
			ord_list.qc_flag,   
			ord_list.part_type,   
			cust_xref.cust_part,   
			inv_master.lb_tracking,   
			ord_list.orig_part_no,   
			inv_master.allow_fractions,   
			ord_list.back_ord_flag,   
			ord_list.gl_rev_acct,   
			ord_list.total_tax,   
			ord_list.tax_code,   
			ord_list.weight_ea,   
			ord_list.display_line,   
			ord_list.curr_price,   
			ord_list.oper_price,   
			dbo.ord_list.ordered * 0 c_released,   
			ord_list.std_direct_dolrs,   
			ord_list.std_ovhd_dolrs,   
			ord_list.std_util_dolrs,   
			UPPER(dbo.inv_master.status) _part_type,   
			dbo.ord_list.price * 0 _alt_price,   
			space(100) _curr_mask,   
			dbo.ord_list.line_no * 0 _curr_precision,   
			inv_master.status,   
			ord_list.reference_code,   
			ord_list.contract,   
			space(35) _tdc_status,   
			ord_list.ship_to,   
			adm_shipto_all.ship_to_name,   
			adm_shipto_all.addr2,   
			adm_shipto_all.addr3,   
			adm_shipto_all.addr4,   
			adm_shipto_all.addr5,   
			adm_shipto_all.addr6,   
			adm_shipto_all.ship_via_code,   
			adm_shipto_all.fob_code,   
			adm_shipto_all.forwarder_code,   
			adm_shipto_all.territory_code,   
			adm_shipto_all.dest_zone_code,   
			adm_shipto_all.special_instr,   
			adm_shipto_all.contact_name,   
			adm_shipto_all.contact_phone,   
			adm_shipto_all.city,   
			adm_shipto_all.state,   
			adm_shipto_all.postal_code,   
			adm_shipto_all.country,   
			UPPER(dbo.ord_list.status) _multiple,   
			ord_list.service_agreement_flag,
			UPPER(dbo.ord_list.status) _job_status,
			ord_list.inv_available_flag,
			1 alt_flag,
			ord_list.create_po_flag,
			ord_list.load_group_no,
			ord_list.return_code,
			ord_list.user_count,
			0.0 _margin_type,
			inv_master.serial_flag,
			case when t.so_cnt > 1 then 'Multiple' else t.po_no end,
			inv_master.min_profit_perc,
			NULL _available,
			isnull(orders.eprocurement_ind,0),
			CASE WHEN EXISTS(SELECT * FROM notes (NOLOCK) WHERE code_type = 'O' AND code = CAST(ord_list.order_no AS VARCHAR) AND line_no = ord_list.line_no) THEN 'Y' ELSE 'N' END add_note,
			ord_list.cust_po,
			-1 disable_acct,
			ord_list.organization_id,
			isnull(orders.internal_so_ind,0) internal_so_ind,
			CVO_ord_list.order_no,
			CVO_ord_list.order_ext,
			CVO_ord_list.line_no,
			CVO_ord_list.add_case,
			CVO_ord_list.add_pattern,
			CVO_ord_list.from_line_no,
			CVO_ord_list.is_case,
			CVO_ord_list.is_pattern,
			0 _from_display_line,
			CVO_ord_list.add_polarized,
			CVO_ord_list.is_polarized,
			CVO_ord_list.is_pop_gif,
			inv_master.category,
			inv_master.type_code,
			CVO_ord_list.is_amt_disc,
			CVO_ord_list.amt_disc,
			CVO_ord_list.is_customized,
			CVO_ord_list.promo_item,
			CVO_ord_list.list_price,
			NULL _replen_qty,
			CVO_ord_list.free_frame,
			cvo_ord_list.due_date,
			ord_list.who_unpicked_id, -- v1.1
			CVO_ord_list.upsell_flag,
-- v1.5			CASE WHEN EXISTS(SELECT 1 FROM tdc_soft_alloc_tbl (NOLOCK) WHERE order_type = 'S' AND order_no = ord_list.order_no AND order_ext = ord_list.order_ext) THEN 'Y' ELSE 'N' END is_allocated -- v1.3 v1.4 Remove line no
			CASE WHEN orders.user_def_fld11 = 0 THEN 'N' ELSE 'Y' END is_allocated -- v1.5
	FROM	ord_list
    left outer join cust_xref (nolock) on ( ord_list.part_no = cust_xref.part_no) and ( dbo.cust_xref.customer_key = @custkey )
    left outer join inv_master (nolock) on ( ord_list.part_no = inv_master.part_no)
    left outer join adm_shipto_all (nolock) on ( ord_list.ship_to = adm_shipto_all.ship_to_code) and ( dbo.adm_shipto_all.customer_code = @custkey )
	join orders (nolock) on ( orders.order_no = ord_list.order_no and orders.ext = ord_list.order_ext)
	left outer join (select part_no, location, order_no, line_no, min(po_no),count(*) from orders_auto_po oap (nolock) 
					where po_no is not null group by part_no, location, order_no, line_no) as t(part_no, location, order_no, line_no, po_no, so_cnt)
	on	t.part_no = ord_list.part_no and t.location = ord_list.location and
		 t.order_no = ord_list.order_no and t.line_no = ord_list.line_no
	left outer join CVO_ord_list ON ord_list.order_no = CVO_ord_list.order_no AND ord_list.order_ext = CVO_ord_list.order_ext AND ord_list.line_no = CVO_ord_list.line_no
	WHERE ( ( dbo.ord_list.order_no = @order_no ) AND  
         ( dbo.ord_list.order_ext = @order_ext ) )   
	ORDER BY ord_list.order_no ASC, ord_list.order_ext ASC, ord_list.line_no ASC  

END
GO
GRANT EXECUTE ON  [dbo].[cvo_scm_pb_get_dw_orders_newlist] TO [public]
GO
