SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		ELABARBERA
-- Create date: 3/13/2013
-- Description:	NEW CUSTOMERS REPORT
-- EXEC SSRS_NEW_CUSTS_SP '2013'
-- =============================================
CREATE PROCEDURE [dbo].[SSRS_NEW_CUSTS_SP]
@YEAR VARCHAR(10)
AS
BEGIN
	SET NOCOUNT ON;

--DECLARE @YEAR VARCHAR(10)
DECLARE @DATE DATETIME
--SET @YEAR = '2013'
SET @Date = ('1/1/'+@YEAR)

select Customer_code, addr_sort1, added_by_date, 
CASE 
	WHEN ADDED_BY_DATE between @DATE and DATEADD(S,-1,(DATEADD(MM,1,@DATE))) THEN '01-JAN'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,2,@DATE))) THEN '02-FEB'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,3,@DATE))) THEN '03-MAR'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,4,@DATE))) THEN '04-APR'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,5,@DATE))) THEN '05-MAY'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,6,@DATE))) THEN '06-JUN'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,7,@DATE))) THEN '07-JUL'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,8,@DATE))) THEN '08-AUG'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,9,@DATE))) THEN '09-SEP'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,10,@DATE))) THEN '10-OCT'
	WHEN ADDED_BY_DATE between DATEADD(MM,1,@DATE) and DATEADD(S,-1,(DATEADD(MM,11,@DATE))) THEN '11-NOV'
	ELSE '12-DEC' END AS MONTH
from armaster 
where added_by_date between ('1/1/'+@YEAR) and ('12/31/'+@YEAR+' 23:59:59')
and address_type=0
and customer_code>'047200'
and customer_code <'900000'

END
GO
