SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- EXEC dbo.cvo_scm_pb_get_dw_orders 1420576, 0

CREATE PROC [dbo].[cvo_scm_pb_get_dw_orders]	@order_no int, 
											@order_ext int 
AS
BEGIN
	SELECT	orders.order_no ,           
			orders.ext ,           
			orders.cust_code ,           
			orders.ship_to ,           
			orders.req_ship_date ,           
			orders.sch_ship_date ,           
			orders.date_shipped ,           
			orders.date_entered ,           
			orders.cust_po ,           
			orders.who_entered ,           
			orders.status ,           
			orders.attention ,           
			orders.phone ,           
			orders.terms ,           
			orders.routing ,           
			orders.total_invoice ,           
			orders.salesperson ,           
			orders.tax_perc ,           
			orders.invoice_no ,           
			orders.fob ,           
			orders.freight ,           
			orders.printed ,           
			orders.discount ,           
			orders.cancel_date ,           
			orders.label_no ,           
			orders.new ,           
			orders.ship_to_name ,           
			orders.ship_to_add_1 ,           
			orders.ship_to_add_2 ,           
			orders.ship_to_city ,           
			orders.ship_to_state ,           
			orders.ship_to_zip ,           
			orders.ship_to_region ,           
			orders.total_amt_order ,           
			orders.tax_id ,           
			orders.cash_flag ,           
			orders.special_instr ,           
			orders.type ,           
			orders.note ,           
			orders.void ,           
			orders.void_who ,           
			orders.void_date ,           
			orders.changed ,           
			orders.remit_key ,           
			orders.forwarder_key ,           
			orders.freight_to ,           
			orders.sales_comm ,           
			orders.freight_allow_pct ,           
			orders.invoice_date ,           
			orders.back_ord_flag ,           
			orders.route_code ,           
			orders.route_no ,           
			orders.date_printed ,           
			orders.date_transfered ,           
			orders.cr_invoice_no ,           
			orders.cust_dfpa ,           
			orders.who_picked ,           
			orders.location ,           
			orders.ship_to_country ,           
			orders.total_tax ,           
			orders.total_discount ,           
			orders.f_note ,           
			orders.blanket ,           
			orders.gross_sales ,           
			orders.curr_factor ,           
			orders.curr_key ,           
			orders.curr_type ,           
			orders.freight_allow_type ,           
			orders.ship_to_add_3 ,           
			orders.bill_to_key ,           
			orders.load_no ,           
			orders.ship_to_add_4 ,           
			orders.ship_to_add_5 ,           
			orders.oper_factor ,           
			orders.tot_ord_tax ,           
			orders.tot_ord_disc ,           
			orders.tot_ord_freight ,           
			orders.posting_code ,           
			orders.rate_type_home ,           
			orders.rate_type_oper ,           
			orders.reference_code ,           
			orders.hold_reason ,           
			orders.dest_zone_code ,           
			orders.so_priority_code ,           
			adm_cust_all.customer_code ,           
			adm_cust_all.customer_name ,           
			adm_cust_all.addr1 ,           
			adm_cust_all.addr2 ,           
			adm_cust_all.addr3 ,           
			adm_cust_all.addr4 ,           
			adm_cust_all.addr5 ,           
			adm_cust_all.addr6 ,           
			adm_cust_all.state ,           
			adm_cust_all.postal_code ,           
			adm_cust_all.country ,           
			adm_cust_all.contact_name ,          
			adm_cust_all.price_code ,           
			adm_cust_all.credit_limit ,           
			adm_cust_all.one_cur_cust ,           
			glcurr_vw.currency_mask ,           
			glcurr_vw.rounding_factor ,           
			glcurr_vw.curr_precision ,           
			glcurr_vw.position ,           
			orders.orig_no ,           
			orders.orig_ext ,           
			adm_cust_all.payment_code ,           
			adm_cust_all.city ,           
			dbo.orders.total_tax * 0 _weight,           
			dbo.orders.total_tax * 0 _cubic,           
			dbo.orders.total_tax * 0 _ole,           
			dbo.orders.total_tax * 0 _tot_taxable,           
			space(1) _holdquote,           
			adm_cust_all.price_level ,           
			space(100) _tdc_status,           
			orders.multiple_flag ,           
			space(1) _pause_fast_oe,           
			orders.FO_order_no ,     
			adm_cust_all.status_type ,           
			adm_shipto_all.status_type ,                 
			load_master.status,
			orders.user_code,
  			orders.user_priority,
			orders.user_category,
			dbo.orders.consolidate_flag,
			space(1) auto_shipped,
			dbo.orders.blanket_amt,
			dbo.orders.from_date,
			dbo.orders.to_date,
			dbo.orders.sold_to_addr1,
			dbo.orders.sold_to_addr2,
			dbo.orders.sold_to_addr3,
			dbo.orders.sold_to_addr4,
			dbo.orders.sold_to_addr5,
			dbo.orders.sold_to_addr6,
			space(16) _po,
			dbo.orders.total_tax * 0 c_tot_ext_price,
			dbo.orders.eprocurement_ind ,
			dbo.orders.sold_to,
			dbo.orders.user_def_fld1,
			dbo.orders.user_def_fld2,
			dbo.orders.user_def_fld3,
			dbo.orders.user_def_fld4,
			dbo.orders.user_def_fld5,
			dbo.orders.user_def_fld6,
			dbo.orders.user_def_fld7,
			dbo.orders.user_def_fld8,
			dbo.orders.user_def_fld9,
			dbo.orders.user_def_fld10,
			dbo.orders.user_def_fld11,
			dbo.orders.user_def_fld12,
			CASE WHEN EXISTS(SELECT * FROM notes (NOLOCK) WHERE code_type = 'O' AND code = CAST(orders.order_no AS VARCHAR) AND line_no = 0) THEN 'Y' ELSE 'N' END add_note,
			dbo.orders.organization_id,
			isnull((select customer_name from adm_cust_all b (nolock) where ( orders.bill_to_key  = b.customer_code)),'') _bill_to,
			orders.internal_so_ind,
			1 use_ext_cust_ind,
			1 allow_int_cust,
			adm_cust_all.related_org_id,
			orders.ship_to_country_cd,
			orders.sold_to_city,
			orders.sold_to_state,
			orders.sold_to_zip,
			orders.sold_to_country_cd,
			0 _tax_calc_ind,
			isnull(orders.tax_valid_ind,1) tax_valid_ind,
			orders.addr_valid_ind,
			CVO_orders_all.order_no,
			CVO_orders_all.ext,
			CVO_orders_all.add_case,
			CVO_orders_all.add_pattern,
			CVO_orders_all.promo_id,
			CVO_orders_all.promo_level,
			CVO_orders_all.free_shipping,
			CVO_orders_all.split_order,
			CVO_orders_all.flag_print,
			CVO_orders_all.buying_group,
			CVO_orders_all.allocation_date,
			CVO_orders_all.stage_hold,
			CVO_orders_all.replen_inv,
			CVO_orders_all.xfer_no,
			CVO_orders_all.invoice_note,
			CVO_orders_all.commission_override,
			CVO_orders_all.commission_pct,
			CVO_orders_all.st_consolidate,
			CVO_orders_all.email_address,
			CVO_orders_all.upsell_flag,
			CVO_orders_all.must_go_today, -- v1.2
			CASE WHEN ISNULL(cvo_charge_sc.sc_no,0) = 0 THEN 0 ELSE 1 END sc_flag, -- v1.3
			cvo_charge_sc.sc_no, -- v1.3
			ISNULL(cvo_charge_sc.sc_order_no,0) -- v1.3
        FROM orders          
		  left outer join adm_cust_all (nolock) on ( orders.cust_code  = adm_cust_all.customer_code) 
		  left outer join glcurr_vw (nolock) on ( orders.curr_key  = glcurr_vw.currency_code)    
		  left outer join adm_shipto_all (nolock) on ( orders.cust_code  = adm_shipto_all.customer_code)  and     
			( orders.ship_to  = adm_shipto_all.ship_to_code)     
		  left outer join load_master (nolock) on ( orders.load_no  = load_master.load_no) 
		  left outer join CVO_orders_all ON orders.order_no = CVO_orders_all.order_no AND orders.ext = CVO_orders_all.ext
		  left outer join dbo.cvo_charge_sc (NOLOCK) ON orders.order_no = cvo_charge_sc.order_no AND orders.ext = cvo_charge_sc.order_ext -- v1.3
        WHERE ( ( dbo.orders.order_no = @order_no ) and     
			( dbo.orders.ext = @order_ext ) )  
END

GO
GRANT EXECUTE ON  [dbo].[cvo_scm_pb_get_dw_orders] TO [public]
GO
