CREATE TABLE [dbo].[rpt_xferform]
(
[x_xfer_no] [int] NULL,
[x_from_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_req_ship_date] [datetime] NULL,
[x_sch_ship_date] [datetime] NULL,
[x_date_shipped] [datetime] NULL,
[x_date_entered] [datetime] NULL,
[x_req_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_who_entered] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_attention] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_phone] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_routing] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_special_instr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_fob] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_freight] [decimal] (20, 8) NULL,
[x_printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_label_no] [int] NULL,
[x_no_cartons] [int] NULL,
[x_who_shipped] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_date_printed] [datetime] NULL,
[x_who_picked] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_to_loc_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_no_pallets] [int] NULL,
[x_shipper_no] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_shipper_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_cust_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_freight_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x_rec_no] [int] NULL,
[l_xfer_no] [int] NOT NULL,
[l_line_no] [int] NOT NULL,
[l_from_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[l_to_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[l_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[l_description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_time_entered] [datetime] NOT NULL,
[l_ordered] [decimal] (20, 8) NOT NULL,
[l_shipped] [decimal] (20, 8) NOT NULL,
[l_comment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_cost] [decimal] (20, 8) NOT NULL,
[l_com_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_temp_cost] [decimal] (20, 8) NULL,
[l_uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_conv_factor] [decimal] (20, 8) NOT NULL,
[l_std_cost] [decimal] (20, 8) NOT NULL,
[l_from_bin] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_to_bin] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_lot_ser] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_date_expires] [datetime] NULL,
[l_lb_tracking] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_labor] [decimal] (20, 8) NOT NULL,
[l_direct_dolrs] [decimal] (20, 8) NOT NULL,
[l_ovhd_dolrs] [decimal] (20, 8) NOT NULL,
[l_util_dolrs] [decimal] (20, 8) NOT NULL,
[l_display_line] [int] NULL,
[l_qty_rcvd] [decimal] (20, 8) NULL,
[l_reference_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_adj_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_amt_variance] [decimal] (20, 8) NULL,
[lo_location] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_phone] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[v_ship_via_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f_freight_type_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a_note_no] [int] NULL,
[x_back_ord_flag] [int] NOT NULL,
[l_back_ord_flag] [int] NOT NULL,
[bo_xfer_no] [int] NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[rpt_xferform] TO [public]
GO
GRANT SELECT ON  [dbo].[rpt_xferform] TO [public]
GO
GRANT INSERT ON  [dbo].[rpt_xferform] TO [public]
GO
GRANT DELETE ON  [dbo].[rpt_xferform] TO [public]
GO
GRANT UPDATE ON  [dbo].[rpt_xferform] TO [public]
GO
