CREATE TABLE [dbo].[cvo_cust_import]
(
[row_id] [int] NOT NULL IDENTITY(1, 1),
[customer_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___custo__1D985BF5] DEFAULT (''),
[ship_to_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___ship___1E8C802E] DEFAULT (''),
[cust_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___cust___1F80A467] DEFAULT (''),
[addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___addr1__2074C8A0] DEFAULT (''),
[addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___addr2__2168ECD9] DEFAULT (''),
[addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___addr3__225D1112] DEFAULT (''),
[addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___addr4__2351354B] DEFAULT (''),
[city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust_i__city__24455984] DEFAULT (''),
[state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___state__25397DBD] DEFAULT (''),
[postal_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___posta__262DA1F6] DEFAULT (''),
[country] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___count__2721C62F] DEFAULT (''),
[customer_type] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___custo__2815EA68] DEFAULT (''),
[POP_POB] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___POP_P__290A0EA1] DEFAULT (''),
[attention_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___atten__29FE32DA] DEFAULT (''),
[attention_phone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___atten__2AF25713] DEFAULT (''),
[attention_email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___atten__2BE67B4C] DEFAULT (''),
[contact_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___conta__2CDA9F85] DEFAULT (''),
[contact_phone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___conta__2DCEC3BE] DEFAULT (''),
[contact_email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___conta__2EC2E7F7] DEFAULT (''),
[fax_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___fax_n__2FB70C30] DEFAULT (''),
[tax_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___tax_c__30AB3069] DEFAULT (''),
[terms_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___terms__319F54A2] DEFAULT (''),
[fob_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___fob_c__329378DB] DEFAULT (''),
[territory_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___terri__33879D14] DEFAULT (''),
[fin_chg_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___fin_c__347BC14D] DEFAULT (''),
[price_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___price__356FE586] DEFAULT (''),
[payment_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___payme__366409BF] DEFAULT (''),
[statement_flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___state__37582DF8] DEFAULT (''),
[statement_cycle] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___state__384C5231] DEFAULT (''),
[credit_limit] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___credi__3940766A] DEFAULT (''),
[aging_limit] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___aging__3A349AA3] DEFAULT (''),
[aging_check] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___aging__3B28BEDC] DEFAULT (''),
[aging_allowance] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___aging__3C1CE315] DEFAULT (''),
[ship_complete] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___ship___3D11074E] DEFAULT (''),
[BO_RX_sc_flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___BO_RX__3E052B87] DEFAULT (''),
[BO_non_RX_sc_flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___BO_no__3EF94FC0] DEFAULT (''),
[currency_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___curre__3FED73F9] DEFAULT (''),
[carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___carri__40E19832] DEFAULT (''),
[rx_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___rx_ca__41D5BC6B] DEFAULT (''),
[bo_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___bo_ca__42C9E0A4] DEFAULT (''),
[add_cases] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___add_c__43BE04DD] DEFAULT (''),
[add_pattern] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___add_p__44B22916] DEFAULT (''),
[patterns_first] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___patte__45A64D4F] DEFAULT (''),
[cons_shipments] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___cons___469A7188] DEFAULT (''),
[rx_consolidated] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___rx_co__478E95C1] DEFAULT (''),
[allow_subs] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___allow__4882B9FA] DEFAULT (''),
[commission] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___commi__4976DE33] DEFAULT (''),
[comm_perc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___comm___4A6B026C] DEFAULT (''),
[door] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust_i__door__4B5F26A5] DEFAULT (''),
[residential] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___resid__4C534ADE] DEFAULT (''),
[user_category] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___user___4D476F17] DEFAULT (''),
[credit_for_rets] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___credi__4E3B9350] DEFAULT (''),
[freight_chg_flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___freig__4F2FB789] DEFAULT (''),
[chargebacks] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___charg__5023DBC2] DEFAULT (''),
[print_cm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___print__5117FFFB] DEFAULT (''),
[co_op_eligible] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___co_op__520C2434] DEFAULT (''),
[co_op_thres_flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___co_op__5300486D] DEFAULT (''),
[co_op_thres_amt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___co_op__53F46CA6] DEFAULT (''),
[co_op_rate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___co_op__54E890DF] DEFAULT (''),
[co_op_notes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___co_op__55DCB518] DEFAULT (''),
[metal_plastic] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___metal__56D0D951] DEFAULT (''),
[suns_optical] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___suns___57C4FD8A] DEFAULT (''),
[max_dollars] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust___max_d__58B921C3] DEFAULT (''),
[url] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__cvo_cust_im__url__59AD45FC] DEFAULT (''),
[process] [int] NULL CONSTRAINT [DF__cvo_cust___proce__5AA16A35] DEFAULT ((0)),
[errormessage] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[cvo_cust_import] TO [public]
GO
GRANT INSERT ON  [dbo].[cvo_cust_import] TO [public]
GO
GRANT DELETE ON  [dbo].[cvo_cust_import] TO [public]
GO
GRANT UPDATE ON  [dbo].[cvo_cust_import] TO [public]
GO
