CREATE TABLE [dbo].[SSI_PART_1]
(
[PARTITIONID] [int] NOT NULL,
[PARTNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORMULA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULTNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMODIFIEDBY] [int] NOT NULL,
[LASTMODIFIED] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARTNOTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_PART_1] ADD CONSTRAINT [PK__SSI_PART_1__589F8519] PRIMARY KEY CLUSTERED  ([PARTITIONID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_PART_1] ADD CONSTRAINT [FK__SSI_PART___LASTM__5993A952] FOREIGN KEY ([LASTMODIFIEDBY]) REFERENCES [dbo].[SSI_USR] ([USERID])
GO
GRANT SELECT ON  [dbo].[SSI_PART_1] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_PART_1] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_PART_1] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_PART_1] TO [epicoradmin]
GO
GRANT SELECT ON  [dbo].[SSI_PART_1] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_PART_1] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_PART_1] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_PART_1] TO [public]
GO
