CREATE TABLE [dbo].[rpt_sopickform]
(
[r_rcd_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_order_no] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ext] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_cust_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_date_entered] [datetime] NULL,
[o_req_ship_date] [datetime] NULL,
[o_sch_ship_date] [datetime] NULL,
[o_ship_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_region] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_phone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_freight] [decimal] (20, 8) NULL,
[o_cust_po] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_terms] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_routing] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_fob] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_salesperson] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_customer_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr6] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_postal_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_contact_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_inv_comment_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_attention] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_display_line] [int] NULL,
[l_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_ordered] [decimal] (20, 8) NULL,
[l_shipped] [decimal] (20, 8) NULL,
[l_price] [decimal] (20, 8) NULL,
[l_lb_tracking] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i_bin_no] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i_uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i_in_stock] [decimal] (20, 8) NULL,
[i_commit_ed] [decimal] (20, 8) NULL,
[i_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_lot_ser] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bin_no] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_qty] [decimal] (20, 8) NULL,
[b_uom_qty] [decimal] (20, 8) NULL,
[o_special_instr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i_description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[k_msg] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_part_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_back_ord_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_load_no] [int] NULL,
[l_line] [int] NULL,
[l_ord_precision] [int] NULL,
[l_shp_precision] [int] NULL,
[l_price_precision] [int] NULL,
[b_qty_precision] [int] NULL,
[v_ship_via_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[s_order_ext] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_masked_phone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_dec_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_thou_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pcppf] [int] NULL,
[order_ind] [int] NULL,
[notes_ind] [int] NULL,
[o_who_entered] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_organization_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_extended_name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[rpt_sopickform] TO [public]
GO
GRANT SELECT ON  [dbo].[rpt_sopickform] TO [public]
GO
GRANT INSERT ON  [dbo].[rpt_sopickform] TO [public]
GO
GRANT DELETE ON  [dbo].[rpt_sopickform] TO [public]
GO
GRANT UPDATE ON  [dbo].[rpt_sopickform] TO [public]
GO
