CREATE TABLE [dbo].[SSI_PRFM_1]
(
[PARAMETERID] [int] NOT NULL,
[FIELDENUM] [int] NOT NULL,
[FIELDNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORMULA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_PRFM_1] ADD CONSTRAINT [FK__SSI_PRFM___PARAM__69CA111B] FOREIGN KEY ([PARAMETERID]) REFERENCES [dbo].[SSI_PARM_1] ([PARAMETERID])
GO
GRANT SELECT ON  [dbo].[SSI_PRFM_1] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_PRFM_1] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_PRFM_1] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_PRFM_1] TO [epicoradmin]
GO
GRANT SELECT ON  [dbo].[SSI_PRFM_1] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_PRFM_1] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_PRFM_1] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_PRFM_1] TO [public]
GO
