CREATE TABLE [dbo].[EFORECAST_FORECAST]
(
[SESSIONID] [int] NOT NULL,
[TIMEID] [int] NOT NULL,
[PRODUCTID] [int] NOT NULL,
[LOCATIONID] [int] NOT NULL,
[PROMOID] [int] NOT NULL,
[FORECAST] [real] NULL,
[NOTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTMENT] [decimal] (20, 8) NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EFORECAST_FORECAST_1] ON [dbo].[EFORECAST_FORECAST] ([PRODUCTID], [LOCATIONID], [TIMEID], [SESSIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [efore1] ON [dbo].[EFORECAST_FORECAST] ([SESSIONID], [LOCATIONID], [PRODUCTID], [TIMEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_FORECAST] ADD CONSTRAINT [FK_EFORECAST_FORECAST_EFORECAST_LOCATION_LOCATIONID] FOREIGN KEY ([LOCATIONID]) REFERENCES [dbo].[EFORECAST_LOCATION] ([LOCATIONID])
GO
ALTER TABLE [dbo].[EFORECAST_FORECAST] ADD CONSTRAINT [FK_EFORECAST_FORECAST_EFORECAST_PRODUCT_PRODUCTID] FOREIGN KEY ([PRODUCTID]) REFERENCES [dbo].[EFORECAST_PRODUCT] ([PRODUCTID])
GO
ALTER TABLE [dbo].[EFORECAST_FORECAST] ADD CONSTRAINT [FK_EFORECAST_FORECAST_EFORECAST_PROMO_PROMOID] FOREIGN KEY ([PROMOID]) REFERENCES [dbo].[EFORECAST_PROMO] ([PROMOID])
GO
ALTER TABLE [dbo].[EFORECAST_FORECAST] ADD CONSTRAINT [FK_EFORECAST_FORECAST_EFORECAST_TIME_TIMEID] FOREIGN KEY ([TIMEID]) REFERENCES [dbo].[EFORECAST_TIME] ([TIMEID])
GO
GRANT SELECT ON  [dbo].[EFORECAST_FORECAST] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[EFORECAST_FORECAST] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[EFORECAST_FORECAST] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_FORECAST] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_FORECAST] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_FORECAST] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_FORECAST] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_FORECAST] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_FORECAST] TO [public]
GO
