CREATE TABLE [dbo].[cvo_revo_item_tbl]
(
[part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmi_model_id] [smallint] NULL,
[Collection] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectionName] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[model] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sku] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[short_model] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryDemographic] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[target_age] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eye_shape] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RES_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[case_part] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[frame_category] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[front_material] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temple_material] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nose_pads] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hinge_type] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[release_date] [datetime] NULL,
[prim_img] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorGroupCode] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorName] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialty_fit] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[web_saleable_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eye_size] [float] NULL,
[a_size] [decimal] (18, 1) NULL,
[b_size] [decimal] (18, 1) NULL,
[ed_size] [decimal] (18, 1) NULL,
[dbl_size] [float] NULL,
[temple_size] [decimal] (18, 1) NULL,
[dim_unit] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temple_tip_material] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sun_lens_color] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suns_only] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lens_base] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[front_price] [float] NULL,
[temple_price] [float] NULL,
[wholesale_price] [float] NULL,
[retail_price] [float] NULL,
[progressive_type] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[component_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[component_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[component_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare_temple_length] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asterisk_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asterisk_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asterisk_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[varImported] [smallint] NULL,
[varImportDate] [datetime] NULL,
[variant_release_date] [datetime] NULL,
[model_id] [smallint] NULL,
[variant_id] [smallint] NULL,
[dim_id] [smallint] NULL,
[wsht_id] [smallint] NULL,
[clips_available] [smallint] NULL,
[ispolarizedavailable] [smallint] NULL,
[supplier] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country_origin] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[frame_cost] [float] NULL,
[front_cost] [float] NULL,
[temple_cost] [float] NULL,
[cost_currency] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[single_cable_cost] [float] NULL,
[ws_ship1_qty] [int] NULL,
[ws_ship2_qty] [int] NULL,
[ws_ship3_qty] [int] NULL,
[img_34] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[img_temple] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[img_front] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[img_sku] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[print_flag] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upc_code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_added] [datetime] NULL,
[dim_release_date] [datetime] NULL
) ON [PRIMARY]
GO
