CREATE TABLE [dbo].[EFORECAST_TIME]
(
[TIMEID] [int] NOT NULL,
[YEAR_QUARTER] [int] NOT NULL,
[FIRST_DAY] [datetime] NOT NULL,
[LABEL] AS (CONVERT([varchar](6),[FIRST_DAY],(112)))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_TIME] ADD CONSTRAINT [PK_EFORECAST_TIME] PRIMARY KEY CLUSTERED  ([TIMEID]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[EFORECAST_TIME] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_TIME] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_TIME] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_TIME] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_TIME] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_TIME] TO [public]
GO
