CREATE TABLE [dbo].[rpt_aractter]
(
[territory_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[territory_desc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[date_last_inv] [int] NOT NULL,
[date_last_cm] [int] NOT NULL,
[date_last_adj] [int] NOT NULL,
[date_last_wr_off] [int] NOT NULL,
[date_last_pyt] [int] NOT NULL,
[date_last_nsf] [int] NOT NULL,
[date_last_fin_chg] [int] NOT NULL,
[date_last_late_chg] [int] NOT NULL,
[date_last_comm] [int] NOT NULL,
[amt_last_inv] [float] NOT NULL,
[amt_last_cm] [float] NOT NULL,
[amt_last_adj] [float] NOT NULL,
[amt_last_wr_off] [float] NOT NULL,
[amt_last_pyt] [float] NOT NULL,
[amt_last_nsf] [float] NOT NULL,
[amt_last_fin_chg] [float] NOT NULL,
[amt_last_late_chg] [float] NOT NULL,
[amt_last_comm] [float] NOT NULL,
[last_inv_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_cm_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_adj_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_wr_off_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_pyt_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_nsf_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_fin_chg_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_late_chg_doc] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[high_date_inv] [int] NOT NULL,
[high_date_ar] [int] NOT NULL,
[num_inv] [int] NOT NULL,
[num_inv_paid] [int] NOT NULL,
[num_overdue_pyt] [int] NOT NULL,
[avg_days_pay] [int] NOT NULL,
[avg_days_overdue] [int] NOT NULL,
[last_trx_time] [int] NOT NULL,
[last_inv_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_cm_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_adj_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_wr_off_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_pyt_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_nsf_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_fin_chg_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_late_chg_cur] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[amt1_home] [float] NOT NULL,
[amt2_home] [float] NOT NULL,
[amt3_home] [float] NOT NULL,
[amt4_home] [float] NOT NULL,
[amt5_home] [float] NOT NULL,
[amt6_home] [float] NOT NULL,
[amt_on_order] [float] NOT NULL,
[amt_inv_unposted] [float] NOT NULL,
[high_amt_inv] [float] NOT NULL,
[high_amt_ar] [float] NOT NULL,
[amt_balance] [float] NOT NULL,
[amt1_oper] [float] NOT NULL,
[amt2_oper] [float] NOT NULL,
[amt3_oper] [float] NOT NULL,
[amt4_oper] [float] NOT NULL,
[amt5_oper] [float] NOT NULL,
[amt6_oper] [float] NOT NULL,
[amt_on_order_oper] [float] NOT NULL,
[amt_inv_unposted_oper] [float] NOT NULL,
[high_amt_inv_oper] [float] NOT NULL,
[high_amt_ar_oper] [float] NOT NULL,
[amt_balance_oper] [float] NOT NULL,
[pyt_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[inv_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cm_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[adj_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[wr_off_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[nsf_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[fin_chg_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lt_chg_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[rpt_aractter] TO [public]
GO
GRANT SELECT ON  [dbo].[rpt_aractter] TO [public]
GO
GRANT INSERT ON  [dbo].[rpt_aractter] TO [public]
GO
GRANT DELETE ON  [dbo].[rpt_aractter] TO [public]
GO
GRANT UPDATE ON  [dbo].[rpt_aractter] TO [public]
GO
