CREATE TABLE [dbo].[DRP_DATA]
(
[part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[location] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Collection] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseDate] [datetime] NULL,
[POM] [datetime] NULL,
[Watch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Vendor] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadTime] [smallint] NULL,
[Type_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Material] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartLeadTime] [int] NULL,
[FCost] [decimal] (20, 8) NULL,
[LCost] [decimal] (22, 8) NULL,
[BO] [decimal] (38, 8) NULL,
[RR1] [float] NULL,
[RR3] [float] NULL,
[e4_wu] [int] NULL,
[e12_wu] [int] NULL,
[e26_wu] [int] NULL,
[e52_wu] [int] NULL,
[RL] [decimal] (38, 8) NULL,
[on_hand] [decimal] (38, 8) NULL,
[AvlToProm] [decimal] (38, 8) NULL,
[Alloc] [decimal] (38, 8) NULL,
[alloc1] [decimal] (38, 8) NULL,
[nalloc1] [decimal] (38, 8) NULL,
[FO1] [decimal] (38, 8) NULL,
[alloc2] [decimal] (38, 8) NULL,
[nalloc2] [decimal] (38, 8) NULL,
[FO2] [decimal] (38, 8) NULL,
[alloc3] [decimal] (38, 8) NULL,
[nalloc3] [decimal] (38, 8) NULL,
[FO3] [decimal] (38, 8) NULL,
[alloc4] [decimal] (38, 8) NULL,
[nalloc4] [decimal] (38, 8) NULL,
[FO4] [decimal] (38, 8) NULL,
[alloc5] [decimal] (38, 8) NULL,
[nalloc5] [decimal] (38, 8) NULL,
[FO5] [decimal] (38, 8) NULL,
[alloc6] [decimal] (38, 8) NULL,
[nalloc6] [decimal] (38, 8) NULL,
[FO6] [decimal] (38, 8) NULL,
[avend] [decimal] (38, 8) NULL,
[av4end] [decimal] (38, 8) NULL,
[av8end] [decimal] (38, 8) NULL,
[av12end] [decimal] (38, 8) NULL,
[av16end] [decimal] (38, 8) NULL,
[av20end] [decimal] (38, 8) NULL,
[av24end] [decimal] (38, 8) NULL,
[MOQ] [int] NOT NULL,
[POMoveStyle] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POMovePartNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POMovePeriod] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOQ_tmp] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
