CREATE TABLE [dbo].[EFORECAST_PROMO]
(
[PROMOID] [int] NOT NULL,
[PROMOTION] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMOCODE] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_PROMO] ADD CONSTRAINT [PK_EFORECAST_PROMO] PRIMARY KEY CLUSTERED  ([PROMOID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [EFORECAST_PROMO_IND1] ON [dbo].[EFORECAST_PROMO] ([PROMOCODE]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[EFORECAST_PROMO] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[EFORECAST_PROMO] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_PROMO] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_PROMO] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_PROMO] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_PROMO] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_PROMO] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_PROMO] TO [public]
GO
