CREATE TABLE [dbo].[cvo_cmi_worksheet_data]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[brand] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[model_id] [int] NULL,
[revision_id] [int] NULL,
[cvo_design] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[supplier_style] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sp_terms_sets] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sp_terms_stock] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tooled_sets] [datetime] NULL,
[tooled_sets_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preprod_sets] [datetime] NULL,
[preprod_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vexpo_sets] [datetime] NULL,
[vexpo_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vexpo_sku_assessment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pr_sets] [datetime] NULL,
[pr_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salessets_ship] [datetime] NULL,
[salessets_sail] [datetime] NULL,
[salessets_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship1_ship] [datetime] NULL,
[ship1_sail] [datetime] NULL,
[ship1_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship2_ship] [datetime] NULL,
[ship2_sail] [datetime] NULL,
[ship2_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship3_ship] [datetime] NULL,
[ship3_sail] [datetime] NULL,
[ship3_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[everlight_material] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ws_image] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare1_label] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare1_qty] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare1_unit] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare2_label] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare2_qty] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spare2_unit] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ws_revision] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[special_instructions] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[packaging_instructions] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[full_color_set] [datetime] NULL,
[ship_full_color_set] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pr_sets_10] [datetime] NULL,
[ship_10_pr_sets] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pre_prod_3] [datetime] NULL,
[ship_3_pre_prod] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_ship_retail] [datetime] NULL,
[date_sail_retail] [datetime] NULL,
[ship_ship_retail] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_cancel] [datetime] NULL,
[ship4_ship] [datetime] NULL,
[ship4_sail] [datetime] NULL,
[ship4_type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[cvo_cmi_worksheet_data] ADD CONSTRAINT [PK__cvo_cmi_workshee__2A2F1287] PRIMARY KEY CLUSTERED  ([id]) ON [PRIMARY]
GO
