CREATE TABLE [dbo].[cvo_inv_master_r2_tbl]
(
[part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[item_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collection] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectionName] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[model] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMG_SKU] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMG_WEB] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[img_SpecialtyFit] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Future_ReleaseDate] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prim_img] [int] NULL,
[RES_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryDemographic] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[target_age] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eye_shape] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorGroupCode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorGroupName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorName] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eye_size] [decimal] (20, 8) NULL,
[a_size] [real] NULL,
[b_size] [real] NULL,
[ed_size] [real] NULL,
[dbl_size] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temple_size] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_unit] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[frame_type] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[front_material] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temple_material] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nose_pads] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hinge_type] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sun_lens_color] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sun_material] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sun_lens_type] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialty_fit] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country_of_Origin] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[case_part] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rimless_style] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[front_price] [decimal] (8, 2) NULL,
[temple_price] [decimal] (8, 2) NULL,
[Wholesale_price] [decimal] (20, 8) NULL,
[last_price_upd_date] [datetime] NULL,
[Sugg_Retail_Price] [decimal] (20, 8) NULL,
[release_date] [datetime] NULL,
[upc_code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[web_saleable_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pom_date] [datetime] NULL,
[frame_cost] [decimal] (20, 8) NULL,
[temple_cost] [decimal] (8, 2) NULL,
[cable_cost] [decimal] (8, 2) NULL,
[front_cost] [decimal] (8, 2) NULL,
[vendor] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nat_cur_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ispolarizedavailable] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[progressive_type] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[frame_weight] [decimal] (20, 8) NULL,
[case_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[case_weight] [decimal] (20, 8) NULL,
[PrimaryDemo_Web] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attributes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[special_components] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suns_only] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lens_base] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_brand_model_sku] ON [dbo].[cvo_inv_master_r2_tbl] ([Collection], [model]) INCLUDE ([part_no], [pom_date], [release_date], [RES_type], [web_saleable_flag]) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [idx_part_no_r2] ON [dbo].[cvo_inv_master_r2_tbl] ([part_no]) ON [PRIMARY]
GO
