CREATE TABLE [dbo].[SSI_GPPR_1]
(
[GROUPID] [int] NOT NULL,
[PRODUCTID] [int] NOT NULL,
[LOCATIONID] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_dbo_SSI_GPPR_1_1] ON [dbo].[SSI_GPPR_1] ([PRODUCTID], [LOCATIONID], [GROUPID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_GPPR_1] ADD CONSTRAINT [FK__SSI_GPPR___GROUP__5F4C82A8] FOREIGN KEY ([GROUPID]) REFERENCES [dbo].[SSI_GRP_1] ([GROUPID])
GO
GRANT SELECT ON  [dbo].[SSI_GPPR_1] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_GPPR_1] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_GPPR_1] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_GPPR_1] TO [epicoradmin]
GO
GRANT SELECT ON  [dbo].[SSI_GPPR_1] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_GPPR_1] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_GPPR_1] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_GPPR_1] TO [public]
GO
