CREATE TABLE [dbo].[ord_list_display_line_updated]
(
[timestamp] [timestamp] NOT NULL,
[order_no] [int] NOT NULL,
[order_ext] [int] NOT NULL,
[line_no] [int] NOT NULL,
[location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[time_entered] [datetime] NOT NULL,
[ordered] [decimal] (20, 8) NOT NULL,
[shipped] [decimal] (20, 8) NOT NULL,
[price] [decimal] (20, 8) NOT NULL,
[price_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cost] [decimal] (20, 8) NOT NULL,
[who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_comm] [decimal] (20, 8) NOT NULL,
[temp_price] [decimal] (20, 8) NULL,
[temp_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cr_ordered] [decimal] (20, 8) NOT NULL,
[cr_shipped] [decimal] (20, 8) NOT NULL,
[discount] [decimal] (20, 8) NOT NULL,
[uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[conv_factor] [decimal] (20, 8) NOT NULL,
[void] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[void_who] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[void_date] [datetime] NULL,
[std_cost] [decimal] (20, 8) NOT NULL,
[cubic_feet] [decimal] (20, 8) NOT NULL,
[printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lb_tracking] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[labor] [decimal] (20, 8) NOT NULL,
[direct_dolrs] [decimal] (20, 8) NOT NULL,
[ovhd_dolrs] [decimal] (20, 8) NOT NULL,
[util_dolrs] [decimal] (20, 8) NOT NULL,
[taxable] [int] NULL,
[weight_ea] [decimal] (20, 8) NULL,
[qc_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reason_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row_id] [int] NOT NULL,
[qc_no] [int] NULL,
[rejected] [decimal] (20, 8) NULL,
[part_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orig_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[back_ord_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gl_rev_acct] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_tax] [decimal] (20, 8) NOT NULL,
[tax_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[curr_price] [decimal] (20, 8) NOT NULL,
[oper_price] [decimal] (20, 8) NOT NULL,
[display_line] [int] NOT NULL,
[std_direct_dolrs] [decimal] (20, 8) NULL,
[std_ovhd_dolrs] [decimal] (20, 8) NULL,
[std_util_dolrs] [decimal] (20, 8) NULL,
[reference_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contract] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[agreement_id] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[service_agreement_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_available_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[create_po_flag] [smallint] NULL,
[load_group_no] [int] NULL,
[return_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_count] [int] NULL,
[cust_po] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organization_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[picked_dt] [datetime] NULL,
[who_picked_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed_dt] [datetime] NULL,
[who_unpicked_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unpicked_dt] [datetime] NULL
) ON [PRIMARY]
GO
