CREATE TABLE [dbo].[SSI_PARM_1]
(
[PARAMETERID] [int] NOT NULL,
[PARAMNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARAMTYPE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMODIFIEDBY] [int] NOT NULL,
[LASTMODIFIED] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARAMDESC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_PARM_1] ADD CONSTRAINT [PK__SSI_PARM_1__66EDA470] PRIMARY KEY CLUSTERED  ([PARAMETERID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_PARM_1] ADD CONSTRAINT [FK__SSI_PARM___LASTM__67E1C8A9] FOREIGN KEY ([LASTMODIFIEDBY]) REFERENCES [dbo].[SSI_USR] ([USERID])
GO
GRANT SELECT ON  [dbo].[SSI_PARM_1] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_PARM_1] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_PARM_1] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_PARM_1] TO [epicoradmin]
GO
GRANT SELECT ON  [dbo].[SSI_PARM_1] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_PARM_1] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_PARM_1] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_PARM_1] TO [public]
GO
