CREATE TABLE [dbo].[EFORECAST_CUSTOMER_FORECAST]
(
[TIMEID] [int] NOT NULL,
[PRODUCTID] [int] NOT NULL,
[LOCATIONID] [int] NOT NULL,
[CUST_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QTY] [decimal] (20, 8) NOT NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_CUSTOMER_FORECAST] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_CUSTOMER_FORECAST] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_CUSTOMER_FORECAST] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_CUSTOMER_FORECAST] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_CUSTOMER_FORECAST] TO [public]
GO
