CREATE TABLE [dbo].[cvo_carbi]
(
[as_of_date] [datetime] NULL,
[territory] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slp] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_short_name] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_phone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_opened] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_st_ord_date] [datetime] NULL,
[last_st_order_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discount] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buying] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cstatus] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custnetsales] [float] NULL,
[NetSalesLY] [float] NULL,
[YTDTY] [float] NULL,
[YTDLY] [float] NULL,
[TotAcctNetSales] [float] NULL,
[category] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[style] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_no2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pom_date] [datetime] NULL,
[First_order_date] [datetime] NULL,
[Last_order_date] [datetime] NULL,
[mst12] [float] NULL,
[mst36] [float] NULL,
[mrx12] [float] NULL,
[mrx36] [float] NULL,
[mret12] [float] NULL,
[mret36] [float] NULL,
[mnet12] [float] NULL,
[mnet36] [float] NULL,
[moth12] [float] NULL,
[moth36] [float] NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [idx_cir_cust] ON [dbo].[cvo_carbi] ([cust_code], [ship_to]) ON [PRIMARY]
GO
