CREATE TABLE [dbo].[rpt_bol]
(
[b_bl_no] [int] NULL,
[b_bl_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bl_src_no] [int] NULL,
[b_bl_src_ext] [int] NULL,
[b_bill_to_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_add_1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_add_2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bill_to_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_routing] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_routing_desc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_no_packages] [int] NULL,
[b_cod_amount] [decimal] (20, 8) NULL,
[b_date_shipped] [datetime] NULL,
[b_po_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_skids] [int] NULL,
[b_ship_to_region] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_tare_wt] [decimal] (20, 8) NULL,
[b_freight_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_date_entered] [datetime] NULL,
[b_void] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_void_who] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_void_date] [datetime] NULL,
[b_ship_to_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_notes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_bl_no] [int] NULL,
[l_order_no] [int] NULL,
[l_order_ext] [int] NULL,
[l_line_no] [int] NULL,
[l_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_freight_class] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_time_entered] [datetime] NULL,
[l_shipped] [decimal] (20, 8) NULL,
[l_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_note_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_misc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_weight] [decimal] (20, 8) NULL,
[l_dot] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_hm] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_uom2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_shipped2] [decimal] (20, 8) NULL,
[l_bl_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_po_no] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_conv_factor] [decimal] (20, 8) NULL,
[l_conv_factor2] [decimal] (20, 8) NULL,
[lo_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lo_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[b_currency_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sv_ship_via_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ft_description] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_currency_mask] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_curr_precision] [smallint] NULL,
[g_rounding_factor] [int] NULL,
[g_position] [int] NULL,
[g_neg_num_format] [int] NULL,
[g_symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_symbol_space] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_dec_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_thou_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n_note_cnt] [int] NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[rpt_bol] TO [public]
GO
GRANT SELECT ON  [dbo].[rpt_bol] TO [public]
GO
GRANT INSERT ON  [dbo].[rpt_bol] TO [public]
GO
GRANT DELETE ON  [dbo].[rpt_bol] TO [public]
GO
GRANT UPDATE ON  [dbo].[rpt_bol] TO [public]
GO
