CREATE TABLE [dbo].[SSI_CNVT_1]
(
[CONVERSIONID] [int] NOT NULL,
[MEASURE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONVNOTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMODIFIEDBY] [int] NULL,
[LASTMODIFIED] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONVNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_CNVT_1] ADD CONSTRAINT [FK_SSI_CNVT_2_LASTMOD] FOREIGN KEY ([LASTMODIFIEDBY]) REFERENCES [dbo].[SSI_USR] ([USERID])
GO
GRANT SELECT ON  [dbo].[SSI_CNVT_1] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_CNVT_1] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_CNVT_1] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_CNVT_1] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[SSI_CNVT_1] TO [public]
GO
GRANT SELECT ON  [dbo].[SSI_CNVT_1] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_CNVT_1] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_CNVT_1] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_CNVT_1] TO [public]
GO
