CREATE TABLE [dbo].[rpt_sopackform]
(
[o_order_no] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ext] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_cust_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_req_ship_date] [datetime] NULL,
[o_sch_ship_date] [datetime] NULL,
[o_date_shipped] [datetime] NULL,
[o_date_entered] [datetime] NULL,
[o_cust_po] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_attention] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_phone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_terms] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_routing] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_special_instr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_invoice_date] [datetime] NULL,
[o_total_invoice] [decimal] (20, 8) NULL,
[o_total_amt_order] [decimal] (20, 8) NULL,
[o_salesperson] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_tax_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_tax_perc] [decimal] (20, 8) NULL,
[o_invoice_no] [int] NULL,
[o_fob] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_freight] [decimal] (20, 8) NULL,
[o_printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_discount] [decimal] (20, 8) NULL,
[o_label_no] [int] NULL,
[o_cancel_date] [datetime] NULL,
[o_new] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_add_5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_ship_to_region] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_cash_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_back_ord_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_freight_allow_pct] [decimal] (20, 8) NULL,
[o_route_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_route_no] [decimal] (20, 8) NULL,
[o_date_printed] [datetime] NULL,
[o_date_transfered] [datetime] NULL,
[o_cr_invoice_no] [int] NULL,
[o_who_picked] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_void] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_void_who] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_void_date] [datetime] NULL,
[o_changed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_remit_key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_forwarder_key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_freight_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_sales_comm] [decimal] (20, 8) NULL,
[o_freight_allow_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_cust_dfpa] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_total_tax] [decimal] (20, 8) NULL,
[o_total_discount] [decimal] (20, 8) NULL,
[o_f_note] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_invoice_edi] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_edi_batch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_post_edi_date] [datetime] NULL,
[o_blanket] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_gross_sales] [decimal] (20, 8) NULL,
[o_load_no] [int] NULL,
[o_curr_key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_curr_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_curr_factor] [decimal] (20, 8) NULL,
[o_bill_to_key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_oper_factor] [decimal] (20, 8) NULL,
[o_tot_ord_tax] [decimal] (20, 8) NULL,
[o_tot_ord_disc] [decimal] (20, 8) NULL,
[o_tot_ord_freight] [decimal] (20, 8) NULL,
[o_posting_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_rate_type_home] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_rate_type_oper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_reference_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_hold_reason] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_dest_zone_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_orig_no] [int] NULL,
[o_orig_ext] [int] NULL,
[o_tot_tax_incl] [decimal] (20, 8) NULL,
[o_process_ctrl_num] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_batch_code] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_tot_ord_incl] [decimal] (20, 8) NULL,
[o_barcode_status] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_multiple_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_so_priority_code] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_FO_order_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_line_no] [int] NULL,
[l_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_time_entered] [datetime] NULL,
[l_ordered] [decimal] (20, 8) NULL,
[l_shipped] [decimal] (20, 8) NULL,
[l_price] [decimal] (20, 8) NULL,
[l_price_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_cost] [decimal] (20, 8) NULL,
[l_who_entered] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_sales_comm] [decimal] (20, 8) NULL,
[l_temp_price] [decimal] (20, 8) NULL,
[l_temp_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_cr_ordered] [decimal] (20, 8) NULL,
[l_cr_shipped] [decimal] (20, 8) NULL,
[l_discount] [decimal] (20, 8) NULL,
[l_uom] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_conv_factor] [decimal] (20, 8) NULL,
[l_void] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_void_who] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_void_date] [datetime] NULL,
[l_std_cost] [decimal] (20, 8) NULL,
[l_cubic_feet] [decimal] (20, 8) NULL,
[l_printed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_lb_tracking] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_labor] [decimal] (20, 8) NULL,
[l_direct_dolrs] [decimal] (20, 8) NULL,
[l_ovhd_dolrs] [decimal] (20, 8) NULL,
[l_util_dolrs] [decimal] (20, 8) NULL,
[l_taxable] [int] NULL,
[l_weight_ea] [decimal] (20, 8) NULL,
[l_qc_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_reason_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_row_id] [int] NULL,
[l_qc_no] [int] NULL,
[l_rejected] [decimal] (20, 8) NULL,
[l_part_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_orig_part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_back_ord_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_gl_rev_acct] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_total_tax] [decimal] (20, 8) NULL,
[l_tax_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_curr_price] [decimal] (20, 8) NULL,
[l_oper_price] [decimal] (20, 8) NULL,
[l_display_line] [int] NULL,
[l_std_direct_dolrs] [decimal] (20, 8) NULL,
[l_std_ovhd_dolrs] [decimal] (20, 8) NULL,
[l_std_util_dolrs] [decimal] (20, 8) NULL,
[l_reference_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_contract] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_agreement_id] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_ship_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_service_agreement_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_inv_available_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_ord_precision] [int] NULL,
[l_shp_precision] [int] NULL,
[l_price_precision] [int] NULL,
[c_customer_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_addr6] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_contact_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_inv_comment_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_postal_code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loc_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[v_ship_via_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[s_order_ext] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_masked_phone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_lot_ser] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_bin_no] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b_qty] [decimal] (20, 8) NULL,
[b_uom_qty] [decimal] (20, 8) NULL,
[b_date_expires] [datetime] NULL,
[b_qty_precision] [int] NULL,
[g_dec_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g_thou_separator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_extended_name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT REFERENCES ON  [dbo].[rpt_sopackform] TO [public]
GO
GRANT SELECT ON  [dbo].[rpt_sopackform] TO [public]
GO
GRANT INSERT ON  [dbo].[rpt_sopackform] TO [public]
GO
GRANT DELETE ON  [dbo].[rpt_sopackform] TO [public]
GO
GRANT UPDATE ON  [dbo].[rpt_sopackform] TO [public]
GO
