CREATE TABLE [dbo].[SSI_RURD]
(
[SCHEMAID] [int] NOT NULL,
[RURDOPTIONPOS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CANSAVE] [int] NULL,
[DEFAULTRESYNCH] [int] NULL,
[RURDOPTIONNOTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RURDOPTIONDESC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMODIFIEDBY] [int] NULL,
[LASTMODIFIED] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSI_RURD] ADD CONSTRAINT [FK__SSI_RURD__SCHEMA__54CEF435] FOREIGN KEY ([SCHEMAID]) REFERENCES [dbo].[SSI_SCH] ([SCHEMAID])
GO
GRANT SELECT ON  [dbo].[SSI_RURD] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[SSI_RURD] TO [epicoradmin]
GO
GRANT DELETE ON  [dbo].[SSI_RURD] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[SSI_RURD] TO [epicoradmin]
GO
GRANT SELECT ON  [dbo].[SSI_RURD] TO [public]
GO
GRANT INSERT ON  [dbo].[SSI_RURD] TO [public]
GO
GRANT DELETE ON  [dbo].[SSI_RURD] TO [public]
GO
GRANT UPDATE ON  [dbo].[SSI_RURD] TO [public]
GO
