CREATE TABLE [dbo].[EFORECAST_PRODUCT]
(
[PRODUCTID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PART] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPPLIER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEADTIME] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PART_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FORECAST_FLAG] [int] NOT NULL CONSTRAINT [DF_EFORECAST_PRODUCT_FORECAST_FLAG] DEFAULT ((0)),
[CROSS_REF_PART_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brand] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[style_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pom_date] [datetime] NULL,
[commodity] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_PRODUCT] ADD CONSTRAINT [CK_EFORECAST_PRODUCT_FORECAST_FLAG] CHECK (([FORECAST_FLAG]=(1) OR [FORECAST_FLAG]=(0)))
GO
ALTER TABLE [dbo].[EFORECAST_PRODUCT] ADD CONSTRAINT [PK_EFORECAST_PRODUCT] PRIMARY KEY CLUSTERED  ([PRODUCTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EFORECAST_PRODUCT_IND1] ON [dbo].[EFORECAST_PRODUCT] ([PART], [PRODUCTID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_PRODUCT] ADD CONSTRAINT [FK_EFORECAST_PRODUCT_INV_MASTER_CROSS_REF_PART_NO] FOREIGN KEY ([CROSS_REF_PART_NO]) REFERENCES [dbo].[inv_master] ([part_no])
GO
ALTER TABLE [dbo].[EFORECAST_PRODUCT] ADD CONSTRAINT [FK_EFORECAST_PRODUCT_INV_MASTER_PART_NO] FOREIGN KEY ([PART_NO]) REFERENCES [dbo].[inv_master] ([part_no])
GO
GRANT SELECT ON  [dbo].[EFORECAST_PRODUCT] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_PRODUCT] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_PRODUCT] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_PRODUCT] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_PRODUCT] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_PRODUCT] TO [public]
GO
