CREATE TABLE [dbo].[EFORECAST_LOCATION]
(
[LOCATIONID] [int] NOT NULL,
[LOCATION] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCATION_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SESSIONID] [int] NOT NULL CONSTRAINT [DF_EFORECAST_LOCATION_SESSION_ID] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_LOCATION] ADD CONSTRAINT [PK_EFORECAST_LOCATION] PRIMARY KEY CLUSTERED  ([LOCATIONID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_LOCATION] ADD CONSTRAINT [FK_EFORECAST_LOCATION_LOCATIONS_LOCATION] FOREIGN KEY ([LOCATION]) REFERENCES [dbo].[locations_all] ([location])
GO
GRANT SELECT ON  [dbo].[EFORECAST_LOCATION] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_LOCATION] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_LOCATION] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_LOCATION] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_LOCATION] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_LOCATION] TO [public]
GO
