CREATE TABLE [dbo].[tdc_plw_criteria_templates]
(
[userid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[template_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[template_desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[method] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ship_date_start] [int] NULL,
[ship_date_end] [int] NULL,
[sold_to] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territory] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destination_zone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_status] [int] NULL,
[order_priority_start] [int] NULL,
[order_priority_end] [int] NULL,
[order_priority_range] [int] NULL,
[ship_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_PO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_status_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_category] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[load_no] [int] NULL,
[fill_percent] [int] NULL,
[con_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[type_oper] [int] NULL,
[location_oper] [int] NULL,
[order_status_oper] [int] NULL,
[user_status_oper] [int] NULL,
[ship_to_name_oper] [int] NULL,
[ship_to_city_oper] [int] NULL,
[ship_to_state_oper] [int] NULL,
[ship_to_country_oper] [int] NULL,
[territory_oper] [int] NULL,
[user_category_oper] [int] NULL,
[destination_zone_oper] [int] NULL,
[cust_op1_oper] [int] NULL,
[cust_op2_oper] [int] NULL,
[cust_op3_oper] [int] NULL,
[sold_to_oper] [int] NULL,
[ship_to_oper] [int] NULL,
[load_no_oper] [int] NULL,
[cust_PO_oper] [int] NULL,
[modified_by] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[modified_date] [datetime] NOT NULL,
[delivery_date_start] [int] NULL,
[delivery_date_end] [int] NULL,
[user_hold_oper] [int] NULL,
[user_hold] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[frame_case_match] [int] NULL,
[consolidate_shipment] [int] NULL,
[order_type_oper] [int] NULL,
[order_type_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderby_1] [int] NULL,
[orderby_2] [int] NULL,
[orderby_3] [int] NULL,
[orderby_4] [int] NULL,
[orderby_5] [int] NULL,
[orderby_6] [int] NULL,
[orderby_7] [int] NULL,
[orderby_8] [int] NULL,
[orderby_9] [int] NULL,
[to_loc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_loc_oper] [int] NULL,
[template_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tdc_plw_c__templ__5D846791] DEFAULT ('S'),
[promo_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_id_oper] [int] NULL,
[promo_level] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_level_oper] [int] NULL,
[st_cons_range_start] [int] NULL CONSTRAINT [DF__tdc_plw_c__st_co__70DB5DA4] DEFAULT ((0)),
[st_cons_range_end] [int] NULL CONSTRAINT [DF__tdc_plw_c__st_co__71CF81DD] DEFAULT ((0)),
[st_cons_range] [int] NULL CONSTRAINT [DF__tdc_plw_c__st_co__72C3A616] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tdc_plw_criteria_templates] ADD CONSTRAINT [PK_tdc_plw_criteria_templates] PRIMARY KEY NONCLUSTERED  ([userid], [template_code]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[tdc_plw_criteria_templates] TO [public]
GO
GRANT INSERT ON  [dbo].[tdc_plw_criteria_templates] TO [public]
GO
GRANT DELETE ON  [dbo].[tdc_plw_criteria_templates] TO [public]
GO
GRANT UPDATE ON  [dbo].[tdc_plw_criteria_templates] TO [public]
GO
