CREATE TABLE [dbo].[tdc_cons_filter_set]
(
[consolidation_no] [int] NOT NULL,
[location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[from_location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_status] [int] NOT NULL,
[ship_date_start] [datetime] NOT NULL,
[ship_date_end] [datetime] NOT NULL,
[order_range_start] [int] NULL,
[order_range_end] [int] NULL,
[ext_range_start] [int] NULL,
[ext_range_end] [int] NULL,
[sold_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ship_to] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[territory] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carrier] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destination_zone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_op3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_priority_start] [int] NOT NULL,
[order_priority_end] [int] NOT NULL,
[order_priority_range] [int] NOT NULL,
[order_no_range] [int] NOT NULL,
[ext_no_range] [int] NOT NULL,
[fill_percent] [decimal] (20, 8) NOT NULL,
[orderby_1] [int] NOT NULL,
[orderby_2] [int] NOT NULL,
[orderby_3] [int] NOT NULL,
[orderby_4] [int] NOT NULL,
[orderby_5] [int] NOT NULL,
[orderby_6] [int] NOT NULL,
[orderby_7] [int] NOT NULL,
[order_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ship_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_state] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opt_one_for_one] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__tdc_cons___opt_o__7D82F852] DEFAULT ('N'),
[con_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_PO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_status_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_category] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[load_no] [int] NULL,
[ship_to_name_oper] [int] NULL,
[ship_to_city_oper] [int] NULL,
[ship_to_state_oper] [int] NULL,
[ship_to_country_oper] [int] NULL,
[territory_oper] [int] NULL,
[user_category_oper] [int] NULL,
[destination_zone_oper] [int] NULL,
[cust_op1_oper] [int] NULL,
[cust_op2_oper] [int] NULL,
[cust_op3_oper] [int] NULL,
[sold_to_oper] [int] NULL,
[ship_to_oper] [int] NULL,
[cust_PO_oper] [int] NULL,
[location_oper] [int] NULL,
[load_no_oper] [int] NULL,
[type_oper] [int] NULL,
[user_status_oper] [int] NULL,
[order_status_oper] [int] NULL,
[frame_case_match] [int] NULL,
[orderby_8] [int] NULL,
[orderby_9] [int] NULL,
[order_type_oper] [int] NULL,
[order_type_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consolidate_shipment] [int] NULL,
[delivery_date_start] [datetime] NULL,
[delivery_date_end] [datetime] NULL,
[user_hold_oper] [int] NULL,
[user_hold] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_id_oper] [int] NULL,
[promo_level] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_level_oper] [int] NULL,
[st_cons_range_start] [int] NULL,
[st_cons_range_end] [int] NULL,
[st_cons_range] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tdc_cons_filter_set] ADD CONSTRAINT [PK__tdc_cons_filter___7C8ED419] PRIMARY KEY CLUSTERED  ([consolidation_no]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[tdc_cons_filter_set] TO [public]
GO
GRANT INSERT ON  [dbo].[tdc_cons_filter_set] TO [public]
GO
GRANT DELETE ON  [dbo].[tdc_cons_filter_set] TO [public]
GO
GRANT UPDATE ON  [dbo].[tdc_cons_filter_set] TO [public]
GO
