CREATE TABLE [dbo].[DRP_DATA_NEW]
(
[part_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collection] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseDate] [datetime] NULL,
[POM] [datetime] NULL,
[Watch] [datetime] NULL,
[Status] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CntryOfOrgin] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadTime] [smallint] NULL,
[Type_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part_type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Material] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartLeadTime] [int] NULL,
[FCost] [decimal] (20, 8) NULL,
[LCost] [decimal] (22, 8) NULL,
[1MSold] [float] NOT NULL,
[3MSold] [float] NOT NULL,
[1MRank] [bigint] NOT NULL,
[3MRank] [bigint] NOT NULL,
[1MRankMax] [bigint] NOT NULL,
[3MRankMax] [bigint] NOT NULL,
[ActW1] [decimal] (4, 0) NOT NULL,
[ActW2] [decimal] (4, 0) NOT NULL,
[ActW3] [decimal] (4, 0) NOT NULL,
[ActW4] [decimal] (4, 0) NOT NULL,
[ActW5] [decimal] (4, 0) NOT NULL,
[ActW6] [decimal] (4, 0) NOT NULL,
[ActW7] [decimal] (4, 0) NOT NULL,
[ActW8] [decimal] (4, 0) NOT NULL,
[ActW9] [decimal] (4, 0) NOT NULL,
[ActW10] [decimal] (4, 0) NOT NULL,
[ActW11] [decimal] (4, 0) NOT NULL,
[SubTotal] [decimal] (14, 0) NOT NULL,
[TypeDiff] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NumWks] [int] NOT NULL,
[AvgWk] [decimal] (25, 11) NULL,
[AdjRel_1stOrd] [datetime] NOT NULL,
[wk4] [decimal] (4, 0) NOT NULL,
[wk12] [decimal] (4, 0) NOT NULL,
[wk26] [decimal] (4, 0) NOT NULL,
[wk52] [decimal] (4, 0) NOT NULL,
[TYPE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[av20end] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[e12_WU] [int] NOT NULL,
[e24_WU] [int] NOT NULL,
[e52_WU] [int] NOT NULL
) ON [PRIMARY]
GO
