CREATE TABLE [dbo].[armrinvrpt]
(
[trx_ctrl_num] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[doc_ctrl_num] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_doc] [int] NULL,
[amt_gross] [float] NULL,
[amt_tax] [float] NULL,
[amt_net] [float] NULL,
[unit_price] [float] NULL,
[item_code] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_desc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attention_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attention_phone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlx_twx] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_maint_start] [int] NULL,
[date_maint_end] [int] NULL,
[srp_price] [float] NULL,
[user_count] [int] NULL,
[svc_type_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seller_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pf_inv_ctrl_num] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_no] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_maint_charge] [float] NULL,
[billing_periods] [int] NULL,
[billing_frequency] [int] NULL,
[billing_period_charge] [float] NULL,
[nat_cur_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fixed_charge_type] [int] NULL,
[fixed_charge_percent] [int] NULL,
[fixed_charge_amt] [float] NULL,
[description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_company_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[arco_addr6] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[use_user_count] [int] NULL,
[curr_precision] [smallint] NULL,
[symbol] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_addr6] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_attention_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_doc_dt] [datetime] NULL,
[date_maint_start_dt] [datetime] NULL,
[date_maint_end_dt] [datetime] NULL,
[months_covered] [int] NULL,
[amt_paid] [float] NULL,
[sequence_id] [int] NULL,
[print_copy] [smallint] NULL,
[not_prev_printed] [smallint] NULL,
[mail_company_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_addr1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_addr2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_addr3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bank_addr4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account_no] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[routing_no] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other_data] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[maint_part_no] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_tax] [float] NULL,
[svc_type_desc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[doc_desc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_trx_ctrl_num] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[user_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[armrinvrpt] TO [public]
GO
GRANT INSERT ON  [dbo].[armrinvrpt] TO [public]
GO
GRANT DELETE ON  [dbo].[armrinvrpt] TO [public]
GO
GRANT UPDATE ON  [dbo].[armrinvrpt] TO [public]
GO
