CREATE TABLE [dbo].[EFORECAST_SALESALL]
(
[TIMEID] [int] NOT NULL,
[PRODUCTID] [int] NOT NULL,
[LOCATIONID] [int] NOT NULL,
[PROMOID] [int] NOT NULL,
[UNITS] [real] NULL,
[PRICE] [real] NULL,
[COST] [real] NULL,
[REVENUE] [real] NULL,
[PROFIT] [real] NULL,
[GROSS_SOLD_QTY] [decimal] (20, 8) NULL,
[RETURN_QTY] [decimal] (20, 8) NULL,
[ADJUSTMENT_QTY] [decimal] (20, 8) NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [EFORECAST_SALESALL_IND1] ON [dbo].[EFORECAST_SALESALL] ([LOCATIONID], [PRODUCTID], [TIMEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EFORECAST_SALESALL] ADD CONSTRAINT [FK_EFORECAST_SALESALL_EFORECAST_LOCATION_LOCATIONID] FOREIGN KEY ([LOCATIONID]) REFERENCES [dbo].[EFORECAST_LOCATION] ([LOCATIONID])
GO
ALTER TABLE [dbo].[EFORECAST_SALESALL] ADD CONSTRAINT [FK_EFORECAST_SALESALL_EFORECAST_PRODUCT_PRODUCTID] FOREIGN KEY ([PRODUCTID]) REFERENCES [dbo].[EFORECAST_PRODUCT] ([PRODUCTID])
GO
ALTER TABLE [dbo].[EFORECAST_SALESALL] ADD CONSTRAINT [FK_EFORECAST_SALESALL_EFORECAST_PROMO_PROMOID] FOREIGN KEY ([PROMOID]) REFERENCES [dbo].[EFORECAST_PROMO] ([PROMOID])
GO
ALTER TABLE [dbo].[EFORECAST_SALESALL] ADD CONSTRAINT [FK_EFORECAST_SALESALL_EFORECAST_TIME_TIMEID] FOREIGN KEY ([TIMEID]) REFERENCES [dbo].[EFORECAST_TIME] ([TIMEID])
GO
GRANT SELECT ON  [dbo].[EFORECAST_SALESALL] TO [epicoradmin]
GO
GRANT INSERT ON  [dbo].[EFORECAST_SALESALL] TO [epicoradmin]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_SALESALL] TO [epicoradmin]
GO
GRANT REFERENCES ON  [dbo].[EFORECAST_SALESALL] TO [public]
GO
GRANT SELECT ON  [dbo].[EFORECAST_SALESALL] TO [public]
GO
GRANT INSERT ON  [dbo].[EFORECAST_SALESALL] TO [public]
GO
GRANT DELETE ON  [dbo].[EFORECAST_SALESALL] TO [public]
GO
GRANT UPDATE ON  [dbo].[EFORECAST_SALESALL] TO [public]
GO
