IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cventura')
CREATE LOGIN [CVOPTICAL\cventura] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cventura] FOR LOGIN [CVOPTICAL\cventura] WITH DEFAULT_SCHEMA=[CVOPTICAL\cventura]
GO
