IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jwhite')
CREATE LOGIN [CVOPTICAL\jwhite] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jwhite] FOR LOGIN [CVOPTICAL\jwhite] WITH DEFAULT_SCHEMA=[CVOPTICAL\jwhite]
GO
