IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\racosta')
CREATE LOGIN [CVOPTICAL\racosta] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\racosta] FOR LOGIN [CVOPTICAL\racosta] WITH DEFAULT_SCHEMA=[CVOPTICAL\racosta]
GO
