IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\emoore')
CREATE LOGIN [CVOPTICAL\emoore] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\emoore] FOR LOGIN [CVOPTICAL\emoore] WITH DEFAULT_SCHEMA=[CVOPTICAL\emoore]
GO
