IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\GKubicki')
CREATE LOGIN [CVOPTICAL\GKubicki] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\GKubicki] FOR LOGIN [CVOPTICAL\GKubicki] WITH DEFAULT_SCHEMA=[CVOPTICAL\GKubicki]
GO
