IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\srivas')
CREATE LOGIN [CVOPTICAL\srivas] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\srivas] FOR LOGIN [CVOPTICAL\srivas] WITH DEFAULT_SCHEMA=[CVOPTICAL\srivas]
GO
