IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sgooya')
CREATE LOGIN [CVOPTICAL\sgooya] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sgooya] FOR LOGIN [CVOPTICAL\sgooya] WITH DEFAULT_SCHEMA=[CVOPTICAL\sgooya]
GO
