IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lfreccia')
CREATE LOGIN [CVOPTICAL\lfreccia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lfreccia] FOR LOGIN [CVOPTICAL\lfreccia] WITH DEFAULT_SCHEMA=[CVOPTICAL\lfreccia]
GO
