IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\DCarlson')
CREATE LOGIN [CVOPTICAL\DCarlson] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\DCarlson] FOR LOGIN [CVOPTICAL\DCarlson]
GO
