IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\pavelar')
CREATE LOGIN [CVOPTICAL\pavelar] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\pavelar] FOR LOGIN [CVOPTICAL\pavelar] WITH DEFAULT_SCHEMA=[CVOPTICAL\pavelar]
GO
