IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\GGavilanes')
CREATE LOGIN [CVOPTICAL\GGavilanes] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\GGavilanes] FOR LOGIN [CVOPTICAL\GGavilanes] WITH DEFAULT_SCHEMA=[CVOPTICAL\GGavilanes]
GO
