IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\AMongelluzzo')
CREATE LOGIN [CVOPTICAL\AMongelluzzo] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\AMongelluzzo] FOR LOGIN [CVOPTICAL\AMongelluzzo] WITH DEFAULT_SCHEMA=[CVOPTICAL\AMongelluzzo]
GO
