IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rekus')
CREATE LOGIN [CVOPTICAL\rekus] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rekus] FOR LOGIN [CVOPTICAL\rekus] WITH DEFAULT_SCHEMA=[CVOPTICAL\rekus]
GO
