IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\DMcCall')
CREATE LOGIN [CVOPTICAL\DMcCall] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\DMcCall] FOR LOGIN [CVOPTICAL\DMcCall] WITH DEFAULT_SCHEMA=[CVOPTICAL\DMcCall]
GO
