IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\vconroy')
CREATE LOGIN [CVOPTICAL\vconroy] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\vconroy] FOR LOGIN [CVOPTICAL\vconroy] WITH DEFAULT_SCHEMA=[CVOPTICAL\vconroy]
GO
