IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\syousuf')
CREATE LOGIN [CVOPTICAL\syousuf] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\syousuf] FOR LOGIN [CVOPTICAL\syousuf] WITH DEFAULT_SCHEMA=[CVOPTICAL\syousuf]
GO
