IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\svitale')
CREATE LOGIN [CVOPTICAL\svitale] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\svitale] FOR LOGIN [CVOPTICAL\svitale] WITH DEFAULT_SCHEMA=[CVOPTICAL\svitale]
GO
