IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\prodtemp')
CREATE LOGIN [CVOPTICAL\prodtemp] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\prodtemp] FOR LOGIN [CVOPTICAL\prodtemp] WITH DEFAULT_SCHEMA=[CVOPTICAL\prodtemp]
GO
