IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rjenkins')
CREATE LOGIN [CVOPTICAL\rjenkins] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rjenkins] FOR LOGIN [CVOPTICAL\rjenkins] WITH DEFAULT_SCHEMA=[CVOPTICAL\rjenkins]
GO
