IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jmunguia')
CREATE LOGIN [CVOPTICAL\jmunguia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jmunguia] FOR LOGIN [CVOPTICAL\jmunguia] WITH DEFAULT_SCHEMA=[CVOPTICAL\jmunguia]
GO
