IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jlederman')
CREATE LOGIN [CVOPTICAL\jlederman] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jlederman] FOR LOGIN [CVOPTICAL\jlederman] WITH DEFAULT_SCHEMA=[CVOPTICAL\JLEDERMAN]
GO
