IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rbrady')
CREATE LOGIN [CVOPTICAL\rbrady] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rbrady] FOR LOGIN [CVOPTICAL\rbrady] WITH DEFAULT_SCHEMA=[CVOPTICAL\rbrady]
GO
