IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\joconnor')
CREATE LOGIN [CVOPTICAL\joconnor] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\joconnor] FOR LOGIN [CVOPTICAL\joconnor] WITH DEFAULT_SCHEMA=[CVOPTICAL\joconnor]
GO
