IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cclark')
CREATE LOGIN [CVOPTICAL\cclark] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cclark] FOR LOGIN [CVOPTICAL\cclark] WITH DEFAULT_SCHEMA=[CVOPTICAL\cclark]
GO
