IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\vbrandel')
CREATE LOGIN [CVOPTICAL\vbrandel] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\vbrandel] FOR LOGIN [CVOPTICAL\vbrandel] WITH DEFAULT_SCHEMA=[CVOPTICAL\vbrandel]
GO
