IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\acapasso')
CREATE LOGIN [CVOPTICAL\acapasso] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\acapasso] FOR LOGIN [CVOPTICAL\acapasso] WITH DEFAULT_SCHEMA=[CVOPTICAL\acapasso]
GO
