IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\yramos')
CREATE LOGIN [CVOPTICAL\yramos] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\yramos] FOR LOGIN [CVOPTICAL\yramos] WITH DEFAULT_SCHEMA=[CVOPTICAL\yramos]
GO
