IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hpessoa')
CREATE LOGIN [CVOPTICAL\hpessoa] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hpessoa] FOR LOGIN [CVOPTICAL\hpessoa] WITH DEFAULT_SCHEMA=[CVOPTICAL\hpessoa]
GO
