IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sludwig')
CREATE LOGIN [CVOPTICAL\sludwig] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sludwig] FOR LOGIN [CVOPTICAL\sludwig] WITH DEFAULT_SCHEMA=[CVOPTICAL\sludwig]
GO
