IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\epitest1')
CREATE LOGIN [CVOPTICAL\epitest1] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\epitest1] FOR LOGIN [CVOPTICAL\epitest1] WITH DEFAULT_SCHEMA=[CVOPTICAL\epitest1]
GO
