IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cpicon')
CREATE LOGIN [CVOPTICAL\cpicon] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cpicon] FOR LOGIN [CVOPTICAL\cpicon] WITH DEFAULT_SCHEMA=[CVOPTICAL\cpicon]
GO
