IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hpenny')
CREATE LOGIN [CVOPTICAL\hpenny] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hpenny] FOR LOGIN [CVOPTICAL\hpenny] WITH DEFAULT_SCHEMA=[CVOPTICAL\hpenny]
GO
