IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\CWorthington')
CREATE LOGIN [CVOPTICAL\CWorthington] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\CWorthington] FOR LOGIN [CVOPTICAL\CWorthington] WITH DEFAULT_SCHEMA=[CVOPTICAL\CWorthington]
GO
