IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dfaria')
CREATE LOGIN [CVOPTICAL\dfaria] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dfaria] FOR LOGIN [CVOPTICAL\dfaria] WITH DEFAULT_SCHEMA=[CVOPTICAL\dfaria]
GO
