IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\amccall')
CREATE LOGIN [CVOPTICAL\amccall] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\amccall] FOR LOGIN [CVOPTICAL\amccall] WITH DEFAULT_SCHEMA=[CVOPTICAL\amccall]
GO
