IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lsaravia')
CREATE LOGIN [CVOPTICAL\lsaravia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lsaravia] FOR LOGIN [CVOPTICAL\lsaravia] WITH DEFAULT_SCHEMA=[CVOPTICAL\lsaravia]
GO
