IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nhawkins')
CREATE LOGIN [CVOPTICAL\nhawkins] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nhawkins] FOR LOGIN [CVOPTICAL\nhawkins] WITH DEFAULT_SCHEMA=[CVOPTICAL\nhawkins]
GO
