IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lvickers')
CREATE LOGIN [CVOPTICAL\lvickers] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lvickers] FOR LOGIN [CVOPTICAL\lvickers] WITH DEFAULT_SCHEMA=[CVOPTICAL\lvickers]
GO
