IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lavalos')
CREATE LOGIN [CVOPTICAL\lavalos] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lavalos] FOR LOGIN [CVOPTICAL\lavalos] WITH DEFAULT_SCHEMA=[CVOPTICAL\lavalos]
GO
