IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\atrott')
CREATE LOGIN [CVOPTICAL\atrott] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\atrott] FOR LOGIN [CVOPTICAL\atrott] WITH DEFAULT_SCHEMA=[CVOPTICAL\atrott]
GO
