IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\LDAlessandro')
CREATE LOGIN [CVOPTICAL\LDAlessandro] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\LDAlessandro] FOR LOGIN [CVOPTICAL\LDAlessandro] WITH DEFAULT_SCHEMA=[CVOPTICAL\LDAlessandro]
GO
