IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cmacleod')
CREATE LOGIN [CVOPTICAL\cmacleod] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cmacleod] FOR LOGIN [CVOPTICAL\cmacleod] WITH DEFAULT_SCHEMA=[CVOPTICAL\cmacleod]
GO
