IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\AKaufman')
CREATE LOGIN [CVOPTICAL\AKaufman] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\akaufman] FOR LOGIN [CVOPTICAL\AKaufman] WITH DEFAULT_SCHEMA=[CVOPTICAL\akaufman]
GO
