IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\temmett')
CREATE LOGIN [CVOPTICAL\temmett] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\temmett] FOR LOGIN [CVOPTICAL\temmett] WITH DEFAULT_SCHEMA=[CVOPTICAL\temmett]
GO
