IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ljackson')
CREATE LOGIN [CVOPTICAL\ljackson] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ljackson] FOR LOGIN [CVOPTICAL\ljackson] WITH DEFAULT_SCHEMA=[CVOPTICAL\ljackson]
GO
