IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rumanzor')
CREATE LOGIN [CVOPTICAL\rumanzor] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rumanzor] FOR LOGIN [CVOPTICAL\rumanzor] WITH DEFAULT_SCHEMA=[CVOPTICAL\rumanzor]
GO
