IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\abocca')
CREATE LOGIN [CVOPTICAL\abocca] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\abocca] FOR LOGIN [CVOPTICAL\abocca] WITH DEFAULT_SCHEMA=[CVOPTICAL\abocca]
GO
