IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\elowe')
CREATE LOGIN [CVOPTICAL\elowe] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\elowe] FOR LOGIN [CVOPTICAL\elowe] WITH DEFAULT_SCHEMA=[CVOPTICAL\elowe]
GO
