IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\pChajchic')
CREATE LOGIN [CVOPTICAL\pChajchic] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\pChajchic] FOR LOGIN [CVOPTICAL\pChajchic] WITH DEFAULT_SCHEMA=[CVOPTICAL\pChajchic]
GO
