IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ARodriguez')
CREATE LOGIN [CVOPTICAL\ARodriguez] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ARodriguez] FOR LOGIN [CVOPTICAL\ARodriguez] WITH DEFAULT_SCHEMA=[CVOPTICAL\ARodriguez]
GO
