IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jpavone')
CREATE LOGIN [CVOPTICAL\jpavone] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jpavone] FOR LOGIN [CVOPTICAL\jpavone] WITH DEFAULT_SCHEMA=[CVOPTICAL\jpavone]
GO
