IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\Dfriedfeld')
CREATE LOGIN [CVOPTICAL\Dfriedfeld] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\Dfriedfeld] FOR LOGIN [CVOPTICAL\Dfriedfeld] WITH DEFAULT_SCHEMA=[CVOPTICAL\Dfriedfeld]
GO
