IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\stinneny')
CREATE LOGIN [CVOPTICAL\stinneny] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\stinneny] FOR LOGIN [CVOPTICAL\stinneny] WITH DEFAULT_SCHEMA=[CVOPTICAL\stinneny]
GO
