IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\JReimers')
CREATE LOGIN [CVOPTICAL\JReimers] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\JReimers] FOR LOGIN [CVOPTICAL\JReimers] WITH DEFAULT_SCHEMA=[CVOPTICAL\JReimers]
GO
