IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\bwong')
CREATE LOGIN [CVOPTICAL\bwong] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\bwong] FOR LOGIN [CVOPTICAL\bwong] WITH DEFAULT_SCHEMA=[CVOPTICAL\bwong]
GO
