IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\aarce')
CREATE LOGIN [CVOPTICAL\aarce] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\aarce] FOR LOGIN [CVOPTICAL\aarce] WITH DEFAULT_SCHEMA=[CVOPTICAL\aarce]
GO
