IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jgordon')
CREATE LOGIN [CVOPTICAL\jgordon] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jgordon] FOR LOGIN [CVOPTICAL\jgordon] WITH DEFAULT_SCHEMA=[CVOPTICAL\jgordon]
GO
