IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dgooya')
CREATE LOGIN [CVOPTICAL\dgooya] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dgooya] FOR LOGIN [CVOPTICAL\dgooya] WITH DEFAULT_SCHEMA=[CVOPTICAL\dgooya]
GO
