IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\celder')
CREATE LOGIN [CVOPTICAL\celder] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\celder] FOR LOGIN [CVOPTICAL\celder] WITH DEFAULT_SCHEMA=[CVOPTICAL\celder]
GO
