IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\LWaltman')
CREATE LOGIN [CVOPTICAL\LWaltman] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\LWaltman] FOR LOGIN [CVOPTICAL\LWaltman] WITH DEFAULT_SCHEMA=[CVOPTICAL\LWaltman]
GO
