IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\edelcid')
CREATE LOGIN [CVOPTICAL\edelcid] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\edelcid] FOR LOGIN [CVOPTICAL\edelcid] WITH DEFAULT_SCHEMA=[CVOPTICAL\edelcid]
GO
