IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\mkur')
CREATE LOGIN [CVOPTICAL\mkur] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\mkur] FOR LOGIN [CVOPTICAL\mkur] WITH DEFAULT_SCHEMA=[CVOPTICAL\mkur]
GO
