IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jcolon')
CREATE LOGIN [CVOPTICAL\jcolon] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jcolon] FOR LOGIN [CVOPTICAL\jcolon] WITH DEFAULT_SCHEMA=[CVOPTICAL\jcolon]
GO
