IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\aromero')
CREATE LOGIN [CVOPTICAL\aromero] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\aromero] FOR LOGIN [CVOPTICAL\aromero] WITH DEFAULT_SCHEMA=[CVOPTICAL\aromero]
GO
