IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\LFigueroa')
CREATE LOGIN [CVOPTICAL\LFigueroa] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\LFigueroa] FOR LOGIN [CVOPTICAL\LFigueroa] WITH DEFAULT_SCHEMA=[CVOPTICAL\LFigueroa]
GO
