IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nboccia')
CREATE LOGIN [CVOPTICAL\nboccia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nboccia] FOR LOGIN [CVOPTICAL\nboccia] WITH DEFAULT_SCHEMA=[CVOPTICAL\nboccia]
GO
