IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ffunes')
CREATE LOGIN [CVOPTICAL\ffunes] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ffunes] FOR LOGIN [CVOPTICAL\ffunes] WITH DEFAULT_SCHEMA=[CVOPTICAL\ffunes]
GO
