IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lcuoco')
CREATE LOGIN [CVOPTICAL\lcuoco] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lcuoco] FOR LOGIN [CVOPTICAL\lcuoco] WITH DEFAULT_SCHEMA=[CVOPTICAL\lcuoco]
GO
