IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ragar')
CREATE LOGIN [CVOPTICAL\ragar] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ragar] FOR LOGIN [CVOPTICAL\ragar] WITH DEFAULT_SCHEMA=[CVOPTICAL\ragar]
GO
