IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hkaye')
CREATE LOGIN [CVOPTICAL\hkaye] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hkaye] FOR LOGIN [CVOPTICAL\hkaye] WITH DEFAULT_SCHEMA=[CVOPTICAL\hkaye]
GO
