IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\kiuorno')
CREATE LOGIN [CVOPTICAL\kiuorno] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\kiuorno] FOR LOGIN [CVOPTICAL\kiuorno] WITH DEFAULT_SCHEMA=[CVOPTICAL\kiuorno]
GO
