IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\MTarantino')
CREATE LOGIN [CVOPTICAL\MTarantino] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\MTarantino] FOR LOGIN [CVOPTICAL\MTarantino] WITH DEFAULT_SCHEMA=[CVOPTICAL\MTarantino]
GO
