IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rfarooq')
CREATE LOGIN [CVOPTICAL\rfarooq] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rfarooq] FOR LOGIN [CVOPTICAL\rfarooq] WITH DEFAULT_SCHEMA=[CVOPTICAL\rfarooq]
GO
