IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\mdoyle')
CREATE LOGIN [CVOPTICAL\mdoyle] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\mdoyle] FOR LOGIN [CVOPTICAL\mdoyle] WITH DEFAULT_SCHEMA=[CVOPTICAL\mdoyle]
GO
