IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\tkennedy')
CREATE LOGIN [CVOPTICAL\tkennedy] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\tkennedy] FOR LOGIN [CVOPTICAL\tkennedy] WITH DEFAULT_SCHEMA=[CVOPTICAL\tkennedy]
GO
