IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\zzajmi')
CREATE LOGIN [CVOPTICAL\zzajmi] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\zzajmi] FOR LOGIN [CVOPTICAL\zzajmi] WITH DEFAULT_SCHEMA=[CVOPTICAL\zzajmi]
GO
