IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\awatkins')
CREATE LOGIN [CVOPTICAL\awatkins] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\awatkins] FOR LOGIN [CVOPTICAL\awatkins] WITH DEFAULT_SCHEMA=[CVOPTICAL\awatkins]
GO
