IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dgorman')
CREATE LOGIN [CVOPTICAL\dgorman] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dgorman] FOR LOGIN [CVOPTICAL\dgorman] WITH DEFAULT_SCHEMA=[CVOPTICAL\dgorman]
GO
