IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\PLondon')
CREATE LOGIN [CVOPTICAL\PLondon] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\PLondon] FOR LOGIN [CVOPTICAL\PLondon] WITH DEFAULT_SCHEMA=[CVOPTICAL\PLondon]
GO
