IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\CRascoe')
CREATE LOGIN [CVOPTICAL\CRascoe] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\CRascoe] FOR LOGIN [CVOPTICAL\CRascoe] WITH DEFAULT_SCHEMA=[CVOPTICAL\CRascoe]
GO
