IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\gattong')
CREATE LOGIN [CVOPTICAL\gattong] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\gattong] FOR LOGIN [CVOPTICAL\gattong] WITH DEFAULT_SCHEMA=[CVOPTICAL\gattong]
GO
