IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rBerntsen')
CREATE LOGIN [CVOPTICAL\rBerntsen] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rBerntsen] FOR LOGIN [CVOPTICAL\rBerntsen] WITH DEFAULT_SCHEMA=[CVOPTICAL\rBerntsen]
GO
