IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\aalmonte')
CREATE LOGIN [CVOPTICAL\aalmonte] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\aalmonte] FOR LOGIN [CVOPTICAL\aalmonte] WITH DEFAULT_SCHEMA=[CVOPTICAL\aalmonte]
GO
