IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\KMirro')
CREATE LOGIN [CVOPTICAL\KMirro] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\KMirro] FOR LOGIN [CVOPTICAL\KMirro] WITH DEFAULT_SCHEMA=[CVOPTICAL\KMirro]
GO
