IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\JHEALEY')
CREATE LOGIN [CVOPTICAL\JHEALEY] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\JHEALEY] FOR LOGIN [CVOPTICAL\JHEALEY] WITH DEFAULT_SCHEMA=[CVOPTICAL\JHEALEY]
GO
