IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nsiegel')
CREATE LOGIN [CVOPTICAL\nsiegel] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nsiegel] FOR LOGIN [CVOPTICAL\nsiegel] WITH DEFAULT_SCHEMA=[CVOPTICAL\nsiegel]
GO
