IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\kshea')
CREATE LOGIN [CVOPTICAL\kshea] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\kshea] FOR LOGIN [CVOPTICAL\kshea] WITH DEFAULT_SCHEMA=[CVOPTICAL\kshea]
GO
