IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ascarpa')
CREATE LOGIN [CVOPTICAL\ascarpa] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ascarpa] FOR LOGIN [CVOPTICAL\ascarpa] WITH DEFAULT_SCHEMA=[CVOPTICAL\ascarpa]
GO
