IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\KDAgostino')
CREATE LOGIN [CVOPTICAL\KDAgostino] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\KDAgostino] FOR LOGIN [CVOPTICAL\KDAgostino] WITH DEFAULT_SCHEMA=[CVOPTICAL\KDAgostino]
GO
