IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\mborelli')
CREATE LOGIN [CVOPTICAL\mborelli] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\mborelli] FOR LOGIN [CVOPTICAL\mborelli] WITH DEFAULT_SCHEMA=[CVOPTICAL\mborelli]
GO
