IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\stavarez')
CREATE LOGIN [CVOPTICAL\stavarez] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\stavarez] FOR LOGIN [CVOPTICAL\stavarez] WITH DEFAULT_SCHEMA=[CVOPTICAL\stavarez]
GO
