IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\samaya')
CREATE LOGIN [CVOPTICAL\samaya] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\samaya] FOR LOGIN [CVOPTICAL\samaya] WITH DEFAULT_SCHEMA=[CVOPTICAL\samaya]
GO
