IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sduffy')
CREATE LOGIN [CVOPTICAL\sduffy] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sduffy] FOR LOGIN [CVOPTICAL\sduffy] WITH DEFAULT_SCHEMA=[CVOPTICAL\sduffy]
GO
