IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lgarcia')
CREATE LOGIN [CVOPTICAL\lgarcia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lgarcia] FOR LOGIN [CVOPTICAL\lgarcia] WITH DEFAULT_SCHEMA=[CVOPTICAL\lgarcia]
GO
