IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\RFaber')
CREATE LOGIN [CVOPTICAL\RFaber] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\RFaber] FOR LOGIN [CVOPTICAL\RFaber] WITH DEFAULT_SCHEMA=[CVOPTICAL\RFaber]
GO
