IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\pmallia')
CREATE LOGIN [CVOPTICAL\pmallia] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\pmallia] FOR LOGIN [CVOPTICAL\pmallia] WITH DEFAULT_SCHEMA=[CVOPTICAL\pmallia]
GO
