IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\NFagan')
CREATE LOGIN [CVOPTICAL\NFagan] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\NFagan] FOR LOGIN [CVOPTICAL\NFagan] WITH DEFAULT_SCHEMA=[CVOPTICAL\NFagan]
GO
