IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lmieles')
CREATE LOGIN [CVOPTICAL\lmieles] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lmieles] FOR LOGIN [CVOPTICAL\lmieles] WITH DEFAULT_SCHEMA=[CVOPTICAL\lmieles]
GO
