IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\RRodriguez')
CREATE LOGIN [CVOPTICAL\RRodriguez] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\RRodriguez] FOR LOGIN [CVOPTICAL\RRodriguez] WITH DEFAULT_SCHEMA=[CVOPTICAL\RRodriguez]
GO
