IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dyam')
CREATE LOGIN [CVOPTICAL\dyam] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dyam] FOR LOGIN [CVOPTICAL\dyam] WITH DEFAULT_SCHEMA=[CVOPTICAL\dyam]
GO
