IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\IRosario')
CREATE LOGIN [CVOPTICAL\IRosario] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\IRosario] FOR LOGIN [CVOPTICAL\IRosario] WITH DEFAULT_SCHEMA=[CVOPTICAL\IRosario]
GO
