IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\panzora')
CREATE LOGIN [CVOPTICAL\panzora] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\panzora] FOR LOGIN [CVOPTICAL\panzora] WITH DEFAULT_SCHEMA=[CVOPTICAL\panzora]
GO
