IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\awhite')
CREATE LOGIN [CVOPTICAL\awhite] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\awhite] FOR LOGIN [CVOPTICAL\awhite] WITH DEFAULT_SCHEMA=[CVOPTICAL\awhite]
GO
