IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\JMorris')
CREATE LOGIN [CVOPTICAL\JMorris] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\JMorris] FOR LOGIN [CVOPTICAL\JMorris] WITH DEFAULT_SCHEMA=[CVOPTICAL\JMorris]
GO
