IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cmorales')
CREATE LOGIN [CVOPTICAL\cmorales] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cmorales] FOR LOGIN [CVOPTICAL\cmorales] WITH DEFAULT_SCHEMA=[CVOPTICAL\cmorales]
GO
