IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rchabra')
CREATE LOGIN [CVOPTICAL\rchabra] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rchabra] FOR LOGIN [CVOPTICAL\rchabra] WITH DEFAULT_SCHEMA=[CVOPTICAL\rchabra]
GO
