IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lammons')
CREATE LOGIN [CVOPTICAL\lammons] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lammons] FOR LOGIN [CVOPTICAL\lammons] WITH DEFAULT_SCHEMA=[CVOPTICAL\lammons]
GO
