IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\acruz')
CREATE LOGIN [CVOPTICAL\acruz] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\acruz] FOR LOGIN [CVOPTICAL\acruz] WITH DEFAULT_SCHEMA=[CVOPTICAL\acruz]
GO
