IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\abooth')
CREATE LOGIN [CVOPTICAL\abooth] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\abooth] FOR LOGIN [CVOPTICAL\abooth] WITH DEFAULT_SCHEMA=[CVOPTICAL\abooth]
GO
