IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lgeoghan')
CREATE LOGIN [CVOPTICAL\lgeoghan] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lgeoghan] FOR LOGIN [CVOPTICAL\lgeoghan] WITH DEFAULT_SCHEMA=[CVOPTICAL\lgeoghan]
GO
