IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\zrattu')
CREATE LOGIN [CVOPTICAL\zrattu] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\zrattu] FOR LOGIN [CVOPTICAL\zrattu] WITH DEFAULT_SCHEMA=[CVOPTICAL\zrattu]
GO
