IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\gcaputo')
CREATE LOGIN [CVOPTICAL\gcaputo] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\gcaputo] FOR LOGIN [CVOPTICAL\gcaputo] WITH DEFAULT_SCHEMA=[CVOPTICAL\gcaputo]
GO
