IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dclay')
CREATE LOGIN [CVOPTICAL\dclay] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dclay] FOR LOGIN [CVOPTICAL\dclay] WITH DEFAULT_SCHEMA=[CVOPTICAL\dclay]
GO
