IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\KBrush')
CREATE LOGIN [CVOPTICAL\KBrush] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\KBrush] FOR LOGIN [CVOPTICAL\KBrush] WITH DEFAULT_SCHEMA=[CVOPTICAL\KBrush]
GO
