IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\swasiak')
CREATE LOGIN [CVOPTICAL\swasiak] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\swasiak] FOR LOGIN [CVOPTICAL\swasiak] WITH DEFAULT_SCHEMA=[CVOPTICAL\swasiak]
GO
