IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\tHeinz')
CREATE LOGIN [CVOPTICAL\tHeinz] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\tHeinz] FOR LOGIN [CVOPTICAL\tHeinz] WITH DEFAULT_SCHEMA=[CVOPTICAL\tHeinz]
GO
