IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nperalta')
CREATE LOGIN [CVOPTICAL\nperalta] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nperalta] FOR LOGIN [CVOPTICAL\nperalta] WITH DEFAULT_SCHEMA=[CVOPTICAL\nperalta]
GO
