IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\acervone')
CREATE LOGIN [CVOPTICAL\acervone] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\acervone] FOR LOGIN [CVOPTICAL\acervone] WITH DEFAULT_SCHEMA=[CVOPTICAL\acervone]
GO
