IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\awadler')
CREATE LOGIN [CVOPTICAL\awadler] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\awadler] FOR LOGIN [CVOPTICAL\awadler] WITH DEFAULT_SCHEMA=[CVOPTICAL\awadler]
GO
