IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sdelio')
CREATE LOGIN [CVOPTICAL\sdelio] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sdelio] FOR LOGIN [CVOPTICAL\sdelio] WITH DEFAULT_SCHEMA=[CVOPTICAL\sdelio]
GO
