IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jlara')
CREATE LOGIN [CVOPTICAL\jlara] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jlara] FOR LOGIN [CVOPTICAL\jlara] WITH DEFAULT_SCHEMA=[CVOPTICAL\jlara]
GO
