IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\PMckenna')
CREATE LOGIN [CVOPTICAL\PMckenna] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\PMckenna] FOR LOGIN [CVOPTICAL\PMckenna] WITH DEFAULT_SCHEMA=[CVOPTICAL\PMckenna]
GO
