IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\VMartinez')
CREATE LOGIN [CVOPTICAL\VMartinez] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\VMartinez] FOR LOGIN [CVOPTICAL\VMartinez] WITH DEFAULT_SCHEMA=[CVOPTICAL\VMartinez]
GO
