IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\arosen')
CREATE LOGIN [CVOPTICAL\arosen] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\arosen] FOR LOGIN [CVOPTICAL\arosen] WITH DEFAULT_SCHEMA=[CVOPTICAL\sduffy]
GO
