IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\VLibasci')
CREATE LOGIN [CVOPTICAL\VLibasci] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\VLibasci] FOR LOGIN [CVOPTICAL\VLibasci] WITH DEFAULT_SCHEMA=[CVOPTICAL\VLibasci]
GO
