IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\snoriega')
CREATE LOGIN [CVOPTICAL\snoriega] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\snoriega] FOR LOGIN [CVOPTICAL\snoriega] WITH DEFAULT_SCHEMA=[CVOPTICAL\snoriega]
GO
