IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jkearney')
CREATE LOGIN [CVOPTICAL\jkearney] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jkearney] FOR LOGIN [CVOPTICAL\jkearney] WITH DEFAULT_SCHEMA=[CVOPTICAL\jkearney]
GO
