IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hcabral')
CREATE LOGIN [CVOPTICAL\hcabral] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hcabral] FOR LOGIN [CVOPTICAL\hcabral] WITH DEFAULT_SCHEMA=[CVOPTICAL\hcabral]
GO
