IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\kmyles')
CREATE LOGIN [CVOPTICAL\kmyles] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\kmyles] FOR LOGIN [CVOPTICAL\kmyles] WITH DEFAULT_SCHEMA=[CVOPTICAL\kmyles]
GO
