IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cspataro')
CREATE LOGIN [CVOPTICAL\cspataro] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cspataro] FOR LOGIN [CVOPTICAL\cspataro] WITH DEFAULT_SCHEMA=[CVOPTICAL\cspataro]
GO
