IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\DRodriguez')
CREATE LOGIN [CVOPTICAL\DRodriguez] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\DRodriguez] FOR LOGIN [CVOPTICAL\DRodriguez] WITH DEFAULT_SCHEMA=[CVOPTICAL\DRodriguez]
GO
