IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lhinch')
CREATE LOGIN [CVOPTICAL\lhinch] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lhinch] FOR LOGIN [CVOPTICAL\lhinch] WITH DEFAULT_SCHEMA=[CVOPTICAL\lhinch]
GO
