IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rlosardo')
CREATE LOGIN [CVOPTICAL\rlosardo] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rlosardo] FOR LOGIN [CVOPTICAL\rlosardo] WITH DEFAULT_SCHEMA=[CVOPTICAL\rlosardo]
GO
