IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\JMartin')
CREATE LOGIN [CVOPTICAL\JMartin] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\JMartin] FOR LOGIN [CVOPTICAL\JMartin] WITH DEFAULT_SCHEMA=[CVOPTICAL\JMartin]
GO
