IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nmorice')
CREATE LOGIN [CVOPTICAL\nmorice] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nmorice] FOR LOGIN [CVOPTICAL\nmorice] WITH DEFAULT_SCHEMA=[CVOPTICAL\nmorice]
GO
