IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jcassisi')
CREATE LOGIN [CVOPTICAL\jcassisi] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jcassisi] FOR LOGIN [CVOPTICAL\jcassisi] WITH DEFAULT_SCHEMA=[CVOPTICAL\jcassisi]
GO
