IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rfoster')
CREATE LOGIN [CVOPTICAL\rfoster] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rfoster] FOR LOGIN [CVOPTICAL\rfoster] WITH DEFAULT_SCHEMA=[CVOPTICAL\rfoster]
GO
