IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\kwilson')
CREATE LOGIN [CVOPTICAL\kwilson] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\kwilson] FOR LOGIN [CVOPTICAL\kwilson] WITH DEFAULT_SCHEMA=[CVOPTICAL\kwilson]
GO
