IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\bdryer')
CREATE LOGIN [CVOPTICAL\bdryer] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\bdryer] FOR LOGIN [CVOPTICAL\bdryer] WITH DEFAULT_SCHEMA=[CVOPTICAL\bdryer]
GO
