IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\nclarke')
CREATE LOGIN [CVOPTICAL\nclarke] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\nclarke] FOR LOGIN [CVOPTICAL\nclarke] WITH DEFAULT_SCHEMA=[CVOPTICAL\nclarke]
GO
