IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\lbanks')
CREATE LOGIN [CVOPTICAL\lbanks] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\lbanks] FOR LOGIN [CVOPTICAL\lbanks] WITH DEFAULT_SCHEMA=[CVOPTICAL\lbanks]
GO
