IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sellis')
CREATE LOGIN [CVOPTICAL\sellis] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sellis] FOR LOGIN [CVOPTICAL\sellis] WITH DEFAULT_SCHEMA=[CVOPTICAL\sellis]
GO
