IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\TomOConnell')
CREATE LOGIN [CVOPTICAL\TomOConnell] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\TomOConnell] FOR LOGIN [CVOPTICAL\TomOConnell] WITH DEFAULT_SCHEMA=[CVOPTICAL\TomOConnell]
GO
