IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\efisher')
CREATE LOGIN [CVOPTICAL\efisher] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\efisher] FOR LOGIN [CVOPTICAL\efisher] WITH DEFAULT_SCHEMA=[CVOPTICAL\efisher]
GO
