IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cverolla')
CREATE LOGIN [CVOPTICAL\cverolla] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cverolla] FOR LOGIN [CVOPTICAL\cverolla] WITH DEFAULT_SCHEMA=[CVOPTICAL\cverolla]
GO
