IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\dlevy')
CREATE LOGIN [CVOPTICAL\dlevy] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\dlevy] FOR LOGIN [CVOPTICAL\dlevy] WITH DEFAULT_SCHEMA=[CVOPTICAL\dlevy]
GO
