IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\abapat')
CREATE LOGIN [CVOPTICAL\abapat] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\abapat] FOR LOGIN [CVOPTICAL\abapat] WITH DEFAULT_SCHEMA=[CVOPTICAL\abapat]
GO
