IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\BDeFronzo')
CREATE LOGIN [CVOPTICAL\BDeFronzo] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\BDeFronzo] FOR LOGIN [CVOPTICAL\BDeFronzo] WITH DEFAULT_SCHEMA=[CVOPTICAL\BDeFronzo]
GO
