IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\johara')
CREATE LOGIN [CVOPTICAL\johara] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\johara] FOR LOGIN [CVOPTICAL\johara] WITH DEFAULT_SCHEMA=[CVOPTICAL\johara]
GO
