IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jmoore')
CREATE LOGIN [CVOPTICAL\jmoore] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jmoore] FOR LOGIN [CVOPTICAL\jmoore] WITH DEFAULT_SCHEMA=[CVOPTICAL\jmoore]
GO
