IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\mssmith')
CREATE LOGIN [CVOPTICAL\mssmith] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\mssmith] FOR LOGIN [CVOPTICAL\mssmith] WITH DEFAULT_SCHEMA=[CVOPTICAL\mssmith]
GO
