IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\gguo')
CREATE LOGIN [CVOPTICAL\gguo] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\gguo] FOR LOGIN [CVOPTICAL\gguo] WITH DEFAULT_SCHEMA=[CVOPTICAL\gguo]
GO
