IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\MartyMast')
CREATE LOGIN [CVOPTICAL\MartyMast] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\MartyMast] FOR LOGIN [CVOPTICAL\MartyMast] WITH DEFAULT_SCHEMA=[CVOPTICAL\MartyMast]
GO
