IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\Tbegley')
CREATE LOGIN [CVOPTICAL\Tbegley] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\Tbegley] FOR LOGIN [CVOPTICAL\Tbegley] WITH DEFAULT_SCHEMA=[CVOPTICAL\Tbegley]
GO
