IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ksung')
CREATE LOGIN [CVOPTICAL\ksung] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ksung] FOR LOGIN [CVOPTICAL\ksung] WITH DEFAULT_SCHEMA=[CVOPTICAL\ksung]
GO
