IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\klooby')
CREATE LOGIN [CVOPTICAL\klooby] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\klooby] FOR LOGIN [CVOPTICAL\klooby] WITH DEFAULT_SCHEMA=[CVOPTICAL\klooby]
GO
