IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jcoppel')
CREATE LOGIN [CVOPTICAL\jcoppel] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jcoppel] FOR LOGIN [CVOPTICAL\jcoppel] WITH DEFAULT_SCHEMA=[CVOPTICAL\jcoppel]
GO
