IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ahabib')
CREATE LOGIN [CVOPTICAL\ahabib] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ahabib] FOR LOGIN [CVOPTICAL\ahabib] WITH DEFAULT_SCHEMA=[CVOPTICAL\ahabib]
GO
