IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\aanwar')
CREATE LOGIN [CVOPTICAL\aanwar] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\aanwar] FOR LOGIN [CVOPTICAL\aanwar] WITH DEFAULT_SCHEMA=[CVOPTICAL\aanwar]
GO
