IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rkapoor')
CREATE LOGIN [CVOPTICAL\rkapoor] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rkapoor] FOR LOGIN [CVOPTICAL\rkapoor] WITH DEFAULT_SCHEMA=[CVOPTICAL\rkapoor]
GO
