IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\HKaufman')
CREATE LOGIN [CVOPTICAL\HKaufman] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\HKaufman] FOR LOGIN [CVOPTICAL\HKaufman] WITH DEFAULT_SCHEMA=[CVOPTICAL\HKaufman]
GO
