IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\gpearce')
CREATE LOGIN [CVOPTICAL\gpearce] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\gpearce] FOR LOGIN [CVOPTICAL\gpearce] WITH DEFAULT_SCHEMA=[CVOPTICAL\gpearce]
GO
