IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sjohnson')
CREATE LOGIN [CVOPTICAL\sjohnson] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sjohnson] FOR LOGIN [CVOPTICAL\sjohnson] WITH DEFAULT_SCHEMA=[CVOPTICAL\sjohnson]
GO
