IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\ibonilla')
CREATE LOGIN [CVOPTICAL\ibonilla] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\ibonilla] FOR LOGIN [CVOPTICAL\ibonilla] WITH DEFAULT_SCHEMA=[CVOPTICAL\ibonilla]
GO
