IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\cwagner')
CREATE LOGIN [CVOPTICAL\cwagner] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\cwagner] FOR LOGIN [CVOPTICAL\cwagner] WITH DEFAULT_SCHEMA=[CVOPTICAL\cwagner]
GO
