IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\MMogul')
CREATE LOGIN [CVOPTICAL\MMogul] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\MMogul] FOR LOGIN [CVOPTICAL\MMogul] WITH DEFAULT_SCHEMA=[CVOPTICAL\MMogul]
GO
