IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\mraza')
CREATE LOGIN [CVOPTICAL\mraza] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\mraza] FOR LOGIN [CVOPTICAL\mraza] WITH DEFAULT_SCHEMA=[CVOPTICAL\mraza]
GO
