IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\onamkung')
CREATE LOGIN [CVOPTICAL\onamkung] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\onamkung] FOR LOGIN [CVOPTICAL\onamkung] WITH DEFAULT_SCHEMA=[CVOPTICAL\onamkung]
GO
