IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\avespoli')
CREATE LOGIN [CVOPTICAL\avespoli] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\avespoli] FOR LOGIN [CVOPTICAL\avespoli] WITH DEFAULT_SCHEMA=[CVOPTICAL\avespoli]
GO
