IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\PMelko')
CREATE LOGIN [CVOPTICAL\PMelko] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\PMelko] FOR LOGIN [CVOPTICAL\PMelko] WITH DEFAULT_SCHEMA=[CVOPTICAL\PMelko]
GO
