IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\RSeay')
CREATE LOGIN [CVOPTICAL\RSeay] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\RSeay] FOR LOGIN [CVOPTICAL\RSeay] WITH DEFAULT_SCHEMA=[CVOPTICAL\RSeay]
GO
