IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rbryant')
CREATE LOGIN [CVOPTICAL\rbryant] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rbryant] FOR LOGIN [CVOPTICAL\rbryant] WITH DEFAULT_SCHEMA=[CVOPTICAL\rbryant]
GO
