IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hHywell')
CREATE LOGIN [CVOPTICAL\hHywell] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hHywell] FOR LOGIN [CVOPTICAL\hHywell] WITH DEFAULT_SCHEMA=[CVOPTICAL\hHywell]
GO
