IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\brios')
CREATE LOGIN [CVOPTICAL\brios] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\brios] FOR LOGIN [CVOPTICAL\brios] WITH DEFAULT_SCHEMA=[CVOPTICAL\brios]
GO
