IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\sfisher')
CREATE LOGIN [CVOPTICAL\sfisher] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\sfisher] FOR LOGIN [CVOPTICAL\sfisher] WITH DEFAULT_SCHEMA=[CVOPTICAL\sfisher]
GO
