IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\hmujeeb')
CREATE LOGIN [CVOPTICAL\hmujeeb] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\hmujeeb] FOR LOGIN [CVOPTICAL\hmujeeb] WITH DEFAULT_SCHEMA=[CVOPTICAL\hmujeeb]
GO
