IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\NFurci')
CREATE LOGIN [CVOPTICAL\NFurci] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\NFurci] FOR LOGIN [CVOPTICAL\NFurci] WITH DEFAULT_SCHEMA=[CVOPTICAL\NFurci]
GO
