IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\GMunoz')
CREATE LOGIN [CVOPTICAL\GMunoz] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\GMunoz] FOR LOGIN [CVOPTICAL\GMunoz] WITH DEFAULT_SCHEMA=[CVOPTICAL\GMunoz]
GO
