IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\TJeffries')
CREATE LOGIN [CVOPTICAL\TJeffries] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\TJeffries] FOR LOGIN [CVOPTICAL\TJeffries] WITH DEFAULT_SCHEMA=[CVOPTICAL\TJeffries]
GO
