IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\rwiley')
CREATE LOGIN [CVOPTICAL\rwiley] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\rwiley] FOR LOGIN [CVOPTICAL\rwiley] WITH DEFAULT_SCHEMA=[CVOPTICAL\rwiley]
GO
