IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\amorales')
CREATE LOGIN [CVOPTICAL\amorales] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\amorales] FOR LOGIN [CVOPTICAL\amorales] WITH DEFAULT_SCHEMA=[CVOPTICAL\amorales]
GO
