IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\jfuentes')
CREATE LOGIN [CVOPTICAL\jfuentes] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\jfuentes] FOR LOGIN [CVOPTICAL\jfuentes] WITH DEFAULT_SCHEMA=[CVOPTICAL\jfuentes]
GO
