IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CVOPTICAL\bjohns')
CREATE LOGIN [CVOPTICAL\bjohns] FROM WINDOWS
GO
CREATE USER [CVOPTICAL\bjohns] FOR LOGIN [CVOPTICAL\bjohns] WITH DEFAULT_SCHEMA=[CVOPTICAL\bjohns]
GO
